### ISSUE TITLE
Angle backets in matched property mess up search/results

### ISSUE THREAD

**Issue by brunnerh** [TarekRaafat/autoComplete.js#101]
**System Information**
Windows 10
Electron 6.1.6 web view (= Chrome 76, `5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.42.1 Chrome/76.0.3809.146 Electron/6.1.6 Safari/537.36`)
autoComplete 7.2.0

**Describe the bug**
It seems like the key property by default gets written to the autocomplete list as HTML. This can cause these issues:
- Text that looks like a tag disappears
- Poses an XSS vulnerability
- Part of the result disappears on match
- If the key property is escaped, the angle brackets no longer match

**To Reproduce**
1. Add some entries with the `<control>` in them.
2. Search for anything outside of `<control>`, the "tag" will be gone.
3. Or enter any of the letters in `control`, e.g. for `t`:
![image](https://user-images.githubusercontent.com/834235/75729190-59633d00-5cea-11ea-971e-903100b2791e.png)
---
If the key is escaped one can search for the content:
![image](https://user-images.githubusercontent.com/834235/75729406-03db6000-5ceb-11ea-8637-0d59c148fbf1.png)
...but the angle brackets match on the entity string (`&lt;` instead of `<`):
![image](https://user-images.githubusercontent.com/834235/75729453-29686980-5ceb-11ea-807f-647216d96c8e.png)
![image](https://user-images.githubusercontent.com/834235/75729755-42711a80-5ceb-11ea-84e0-ddd485e8cfd2.png)

**Expected behavior**
- The items should probably escape all HTML by default for security reasons.
- The search should be on the text equivalent, not the escaped HTML.

---

By the way, searching for `(` causes an exception because it is not escaped properly:

> Invalid regular expression: /(/: Unterminated group

**Comment by TarekRaafat** [comment]
Hello @brunnerh,

I apologize for the delayed reply.

You could handle that undesired behavior simply by ignoring/escaping any `HTML` in the search query using the `query` API method as shown below.

```js
query: (input) => input.replace(/<[^>]*>/g, ""),
```

Have a nice day! :)
