### ISSUE TITLE
autoComplete keyboard events interfere with original input keyboard events

### ISSUE THREAD

**Issue by eballeste** [TarekRaafat/autoComplete.js#104]
- [x] **Describe the bug**

Let's say I add an event listener to the original input field where I want the user to be able to trigger certain actions by pressing `enter` from within the field. The field is not part of a form with a submit button. When I add autoComplete to the input field and the user uses the keyboard to select an option with the `enter` key, my original event is called first with whatever value was in the input before autoComplete's event takes place. 

Is there something that could be added to the event so that I can add some logic to differentiate between an autocomplete event and my events. 

- [x] **To Reproduce**
https://codepen.io/eballeste/pen/qBdVmYW
1. Type the letter a.
2. Use the keyboard to navigate down to the 'car' option.
3. Press enter on the keyboard to select.
4. Notice how in console, my original event tied to the input gets called first with the value 'a' that I typed in, followed by the value captured in the `onSelection` method of autoComplete.

- [x] **Expected behavior**
Not sure what the expected behavior is but I would like to find a way to determine if the keydown event was triggered by autoComplete or my script event listener.

**Comment by eballeste** [comment]
for now, I'm doing a sloppy setTimeout of 50ms from within my original event which seems to do the trick but I feel like this might backfire on me somehow.

**Comment by TarekRaafat** [comment]
Hello @eballeste,

The issue has been resolved in [v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0) and above please try it and let me know your feedback.

Have a nice day, cheers! :)
