### ISSUE TITLE
data.src called on each triggers

### ISSUE THREAD

**Issue by thomasphilibert** [TarekRaafat/autoComplete.js#106]
Hi all,

Is it normal that data.src is called when i trigger _focusin_ or _focusout_ ? If yes, is possible to tell to autocomplete dont call data.src when  _focusin_ or _focusout_ event ?

I want to force value in the input are necessarily value from the list but when i select value in list, data.src are called with inserted value in input.

```js
      var input = document.querySelector(".airport_autocomplete");

      input.addEventListener("autoComplete", function(event) {
        if(event.detail.event.type === 'focusin'){
          input.value = '';
        }
      });

      new autoComplete({
        selector: ".airport_autocomplete",
        threshold: 3,
        data: {
          src: async () => {
            const source = await fetch('/ajax/autocomplete/airport');
            return await source.json();
          },
          key: ["txt"],
          cache: false,
        },
        trigger: {
          event: ["input", "focusin", "focusout"]
        },
        resultsList: {
          render: true,
          destination: input,
        },
        onSelection: feedback => {
          input.value = feedback.selection.value.txt;
        }
      });
```

**Comment by TarekRaafat** [comment]
Hello @thomasphilibert,

A method of achieving that is dropping the `"focusin"`, `"focusout"` out of the trigger events, and then use an external event listener for the focus events separately.


Let me know your thoughts.

Cheers, and have a good one! :)

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
