### ISSUE TITLE
Cache pre-fetched data in the user's browser

### ISSUE THREAD

**Issue by stevevance** [TarekRaafat/autoComplete.js#108]
**Is your feature request related to a problem? Please describe.**
I am switching from Typeahead.js to autoComplete.js because Typeahead has been unsupported for several years (no improvements or bug fixes). I saw that autoComplete had a "cache" setting, and I assumed it worked like Typeahead and would cache data to the browser's localStorage. The "cache" setting is rather a pre-fetch option. 

**Thoroughly Describe the solution you'd like**
I would like the pre-fetched data to be cached to the browser's localStorage.

**Please provide a few use cases for this feature**
1. In my application there are many street addresses that are very popular and rather than send those street addresses to a geocoder to get their coordinates I can create a dictionary of those popular street addresses and save them to the user's browser for faster access. (I am already caching the geocoder results, so that saves at least one step.)
2. In my application there are "search shortcuts" that link to webpages within the application. These don't change very often and I would like to cache them in the user's browser. 

**Please Describe alternatives you've considered**
Typeahead was the only alternative and I'm moving away from that. 

**Additional context**
The following screenshot shows that I use a JSON file to store a dictionary of "search shortcuts". 
![image](https://user-images.githubusercontent.com/1330459/77272656-b6b23480-6c7f-11ea-8a18-6417e045e8b8.png)

**Comment by TarekRaafat** [comment]
Hello @stevevance,

Hopefully, the below snippet would achieve the results you're after if I got you right.

> LocalStorage Caching Snippet
```js
data: {
    src: async () => {
        // Loading placeholder text
        const query = document.querySelector("#autoComplete_search").value;
        // Fetch External Data Source
        const source = await fetch("/json/search_directory.json");
        // Format data into json
        const data = await source.json();
        // Saves the fetched data into local storage
        localStorage.setItem("acData", JSON.stringify(data));
        // Retrieve the cached data from local storage
        const localData = JSON.parse(localStorage.getItem("acData"));
        // Returns Fetched data
        return localData.directory_items;
    },
    key: ["name", "description"],
    cache: true
}
```

Kindly try it and let me know if it worked.

Cheers, and have a good one! :)

**Comment by rdetert** [comment]
This did not work for me. Whenever I set `cache: true`, an AJAX request is not made.

**Comment by TarekRaafat** [comment]
@rdetert that's odd. Are you fetching a file or making and an API call and what's the error you're getting?

**Comment by rdetert** [comment]
Yes, I am making an API call just like you have in your example. I'm not even seeing the calls being made to the server.

**Comment by TarekRaafat** [comment]
Could you share the code?
