### ISSUE TITLE
rendered-Event

### ISSUE THREAD

**Issue by zippy84** [TarekRaafat/autoComplete.js#112]
We need a rendered-event after this line:

https://github.com/TarekRaafat/autoComplete.js/blob/21a3972cfaba1dad98a6b422a88f0d9f69747035/dist/js/autoComplete.js#L469

Here is a use-case for this event:

```js
const inp = document.getElementById('myinp');

const ev = new Event('input', {
    bubbles: true,
    cancelable: true
});

inp.value = 'a value';

inp.addEventListener('autoComplete_rendered', (e) {
   // do something with the filled and visible list (#autoComplete_list)
   // for example: trigger click of first item 
});

inp.dispatchEvent(ev);
```

**Comment by TarekRaafat** [comment]
Hello @zippy84,

Thanks for your enhancement suggestion, definitely `pre` and `post` rendering event emitters will be nice.

I'll add it to the list.


Have a nice day, cheers! :)

**Comment by nhaberl** [comment]
Any news here ? :)

**Comment by TarekRaafat** [comment]
Hello @nhaberl,

You can follow up the progress of the new version [v8.0](https://github.com/TarekRaafat/autoComplete.js/tree/v8.0.0) that has this enhancement covered including other many enhancements, features, and bug fixes as well.

Please let me know if you need any help or clarification on the new version.


Cheers! :)

**Comment by nhaberl** [comment]
That looks really great!!!
Thanks a lot!
I have quite a big project to do so will wait for your lib.
As it is pure js its my first choice 🙂

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
