### ISSUE TITLE
AutoFocus

### ISSUE THREAD

**Issue by dictosistemas** [TarekRaafat/autoComplete.js#113]
Hi!

It will be great if there is an "autofocus" option, like JqueryUI autocomplete has, please see:

https://api.jqueryui.com/autocomplete/#option-autoFocus

Thanks a lot!

**Comment by sabina-rohman** [comment]
Hi, Is the issue open? Can I please work on it?

**Comment by dictosistemas** [comment]
It would be great!
Please attention that this autofocus refers to focus the first element after some search made in the input.

**Comment by sabina-rohman** [comment]
Thanks. Will do.

**Comment by sabina-rohman** [comment]
@TarekRaafat I created a custom event for listening to the list population and then select the first item:
```
// Highlight first item in the list
  resultsList.addEventListener("onListPopulate", function(){
    highlightSelection(resultsList.childNodes[0]);
  });
```
It works, as in it selects the first item. But the Enter -> `onSelection` wont work because the `liSelected` field keeps getting reset to `undefined`

Any ideas why?

**Comment by sabina-rohman** [comment]
Hi @TarekRaafat  I have submitted a PR for this issue. Please review https://github.com/TarekRaafat/autoComplete.js/pull/127.
Thanks.

**Comment by dictosistemas** [comment]
Hi @sabina-rohman  , @TarekRaafat !

Could you please show an example using this code "Highlight first item in the list".
I cant understand where exactly add this code in my "AutoComplete" object.
Thanks a lot!

**Comment by TarekRaafat** [comment]
Hello @dictosistemas,

Thanks for your patience.

Kindly find an `autoFocus` example that I've prepared for you on [this](https://codepen.io/tarekraafat/pen/QWKgERN?editors=0010) codepen project including comments on each step for clarity.


Please let me know if you need any further clarification or support.

Have a nice day, cheers! :)

**Comment by dictosistemas** [comment]
Hi @TarekRaafat !
That is great!
Thank you so much for your attention!

**Comment by TarekRaafat** [comment]
@dictosistemas you're most welcome anytime! :)

**Comment by dictosistemas** [comment]
Hi @TarekRaafat !
I am trying to solve this problem using other way, because in my case this example did not work.
Could you please tell me if there is an way to simulate the navigation keyboard like key down afeter rendered?
Thanks!

**Comment by TarekRaafat** [comment]
Hello @dictosistemas,

This [example](https://codepen.io/tarekraafat/pen/wvzexmb?editors=0010) gives the same results but in a different approach as per your request through simulating `keyboard` navigation interaction instead of `mouse` click.


Please check it and let me know if this is what you're after or not.


Cheers! :)

**Comment by dictosistemas** [comment]
Hi @TarekRaafat !
Thats worked perfectly!
Thank you so much!

**Comment by TarekRaafat** [comment]
@dictosistemas I'm glad it worked fine!

You're most welcome anytime, have a nice day! :)
