### ISSUE TITLE
Ability to remove the autocomplete object

### ISSUE THREAD

**Issue by Keagel** [TarekRaafat/autoComplete.js#115]
**Thoroughly Describe the solution you'd like**
I would like to be able to completely remove any autocomplete feature of a particular selector whenever I want. For this I can keep references in an array but there is no method to cancel autocompletion.

**Please provide a few use cases for this feature**
1. When you have a toggle-able setting for autocompletion
2. If you have a lot of autocompleted fields and you remove some dynamically

**Comment by TarekRaafat** [comment]
Hello @Keagel,

The issue has been resolved in [v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0) and above please try it and let me know your feedback.


Have a nice day, cheers! :)
