### ISSUE TITLE
"No Results" still triggered when results are returned

### ISSUE THREAD

**Issue by PhantomWatson** [TarekRaafat/autoComplete.js#116]
**System Information**
Windows 10 (64-bit)
Chrome 83.0.4103.97

# Use Case
I have a field that allows users to add a comma-delimited list of tags. I'm implementing autoComplete.js to replace my current auto-complete system, which suggests canonical tags to append to the end of the field.

![image](https://user-images.githubusercontent.com/1965565/84537779-7088d200-acbe-11ea-96bf-062b862d9ff9.png)

# Code
```javascript
setupAutosuggest: function (customTagInputId) {
    const resultsContainerId = customTagInputId + '-results';
    new autoComplete({
        data: {
            src: async () => {
                const customTags = document.getElementById(customTagInputId).value.trim();
                if (customTags === '') {
                    console.log('no input');
                    return [];
                }
                const query = split(customTags).pop();
                console.log('input: ' + query);
                const source = await fetch(`https://api.example.com/v1/tags/autocomplete?term=${query}`);
                const apiResponse = await source.json();
                const data = apiResponse.hasOwnProperty('data') ? apiResponse.data : null;
                if (!data) {
                    console.log('no data received from API');
                    return [];
                }
                let tagSuggestions = [];
                let tagName;
                for (let i = 0; i < data.length; i++) {
                    tagName = data[i].attributes.name;
                    tagSuggestions.push(tagName);
                }
                console.log('suggestions received from API: ' + tagSuggestions.join(', '));
                return tagSuggestions;
            },
            cache: false
        },
        selector: '#' + customTagInputId,    // Input field selector              | (Optional)
        threshold: 3,                        // Min. Chars length to start Engine | (Optional)
        debounce: 300,                       // Post duration for engine to start | (Optional)
        resultsList: {                       // Rendered results list object      | (Optional)
            render: true,
            container: source => {
                source.setAttribute('id', resultsContainerId);

                // Automatically hide results list upon click
                document.getElementById(customTagInputId).addEventListener('autoComplete', function (event) {
                    function hideSearchResults() {
                        const searchResults = document.getElementById(resultsContainerId);
                        while (searchResults.firstChild) {
                            searchResults.removeChild(searchResults.firstChild);
                        }
                        document.removeEventListener('click', hideSearchResults);
                    }
                    document.addEventListener('click', hideSearchResults);
                })
            },
            destination: document.getElementById(customTagInputId),
            position: 'afterend',
            element: 'ul'
        },
        maxResults: 6,                         // Max. number of rendered results | (Optional)
        highlight: true,                       // Highlight matching results      | (Optional)
        resultItem: {                          // Rendered result item            | (Optional)
            content: (data, source) => {
                source.innerHTML = data.match;
            },
            element: 'li'
        },
        noResults: () => {                     // Action script on noResults      | (Optional)
            const result = document.createElement('li');
            result.setAttribute('class', 'no_result autoComplete_result');
            result.setAttribute('tabindex', '1');
            result.innerHTML = 'No Results';
            document.getElementById(resultsContainerId).appendChild(result);
            console.log('no results (supposedly)');
        },
        onSelection: feedback => {             // Action script onSelection event | (Optional)
            const customTagsField = document.getElementById(customTagInputId);
            let customTags = split(customTagsField.value);
            customTags[customTags.length - 1] = feedback.selection.value;
            customTagsField.value = customTags.join(', ') + ', ';
            console.log('selected ' + feedback.selection.value);
        }
    });
};
```

# Results
This works _almost_ perfectly. For the first tag entered, it always works as expected.
![image](https://user-images.githubusercontent.com/1965565/84538257-556a9200-acbf-11ea-91af-b23b16102c4f.png)
### Then
![image](https://user-images.githubusercontent.com/1965565/84538333-77641480-acbf-11ea-97f8-251458fd3944.png)
### But
But for any tag after the first, it always shows "No Results" despite it actually having results.
![image](https://user-images.githubusercontent.com/1965565/84538427-a4b0c280-acbf-11ea-861e-ec73c34356b5.png)
There's nothing interfering with autoComplete.js receiving input correctly and there's nothing different about how the results are being provided to it, so there must be some other mechanism in the core that's incorrectly triggering the "no results" condition. I poked around for a little while and couldn't find anything obvious, so I'm hoping that someone else might be able to either find where the bug is in the core or point out something in my own code that I'm overlooking.

**Comment by PhantomWatson** [comment]
Ah, nevermind. I figured out the part of the library's configuration that I didn't understand. Since I was doing the result filtering on the server side, I needed to disable the filtering that autoComplete.js was doing on the client side by default in its `searchEngine` setting. I added this to make it stop filtering out any results, and now it works as expected:

```javascript
searchEngine: function (query, record) {
    return record;
}
```

Without this, it was comparing the entire chain of tags (e.g. `"foo, bar, bas"`) to the results returned for the incomplete string at the end (e.g. [`"basket"`, `"basil"`, `"base"`]) and not finding any matches.

**Comment by TarekRaafat** [comment]
Hello @PhantomWatson,

I'm glad you've found a solution to your issue!

That's correct. The default `searchEngine` compares the entire given string within the input field while using the `searchEngine` API lets you use a custom algorithm that bypasses the default.


Cheers, have a good day! :)

**Comment by cbastienbaron** [comment]
ho thanks you @PhantomWatson , 2 hour loose with no result hits ! 
 
IMHO this callback searchengine must be in set in default example ping @TarekRaafat

**Comment by KouloukLeGrand** [comment]
@PhantomWatson thank you so much, I had the exact same problem!

As @cbastienbaron said, this should definitely be a default search engine option instead of having to write boilerplate.
There could also be an how-to implement server-side autocompletion!

**Comment by harpreetsb** [comment]
> Ah, nevermind. I figured out the part of the library's configuration that I didn't understand. Since I was doing the result filtering on the server side, I needed to disable the filtering that autoComplete.js was doing on the client side by default in its `searchEngine` setting. I added this to make it stop filtering out any results, and now it works as expected:
> 
> ```js
> searchEngine: function (query, record) {
>     return record;
> }
> ```
> 
> Without this, it was comparing the entire chain of tags (e.g. `"foo, bar, bas"`) to the results returned for the incomplete string at the end (e.g. [`"basket"`, `"basil"`, `"base"`]) and not finding any matches.

after this, the highlight does not work. any suggestions?

**Comment by harpreetsb** [comment]
solved it with highlights
```
searchEngine: function (query, record) 
                    {
                        let capsQuery = self.capitalize(query);
                        if (query.split(' ').length > 1) 
                        {
                            return record;    
                        }
                        else
                        {
                            return record.replace(capsQuery, `<mark>${capsQuery}</mark>`);
                        }
                    },
```
