### ISSUE TITLE
Input Blinking Cursor Position Changes When Arrow Keys Used

### ISSUE THREAD

**Issue by cadday** [TarekRaafat/autoComplete.js#117]
Hi, thanks for the great library. 

I had a small issue with the cursor in the input going to start and end in the input while using up and down arrows to navigate throughout the result list. I think it should not do that so I fixed it with a small block of code. It's jQuery though.

To reproduce:
1. Navigate to demo: https://tarekraafat.github.io/autoComplete.js/demo/
2. Search something and use up and down arrow keys to navigate.
3. You will notice the blinking bar cursor thingy goes to start and end of the input.

`$('.auto-complete-input').on('focus', onInputFocusIn);

$('.auto-complete-input').on('focusout', onInputFocusOut);

function onInputFocusIn(event) {
	$(this).on('keydown', onKeyDown);
}

function onInputFocusOut(event) {
	$(this).off('keydown', onKeyDown);
}

function onKeyDown(event) {
	if (event.which === 38 || event.which === 40) {
	  event.preventDefault();
	}
}`

One other thing is that pressing up key when there is no result throws an error, just wanted to add this one here since I haven't searched the issues for this one.

Cheers.

**Comment by TarekRaafat** [comment]
Hello @cadday,

I apologize for my delayed reply.

Man, that's awesome thank you for the cursor relocation enhancement! I've implemented your concept already but in vanilla not jQuery and it works perfectly as expected.

Regarding the `keyUp` error with no results, thank you for reporting that issue I'm working on a fix for it as well.


Cheers, have a nice day! :)

**Comment by chrmod** [comment]
@TarekRaafat it would be great to have this fix released

**Comment by TarekRaafat** [comment]
Hello @chrmod,

Thanks for your patience and for following up.

This issue has been resolved starting version [v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0) please try it and let me know your feedback.


Have a nice day, cheer! :)
