### ISSUE TITLE
Display Default Results on Focus

### ISSUE THREAD

**Issue by rdetert** [TarekRaafat/autoComplete.js#120]
If you look at how Yelp does it, they give a dropdown of options as soon as the input has focus.

In my case, I'm using autocomplete on a city name search that talks to the server. I'd like to display an option for "Current Location" on focus before there is any typing, though.

Is this possible?

**Comment by TarekRaafat** [comment]
Hello @rdetert,

Sure, it is possible. Check this [example](https://codepen.io/tarekraafat/pen/dyGVZoo?editors=0010) hopefully this is the result you're looking for. 

Cheers! :)
