### ISSUE TITLE
Display all results on focus, even if a query is given in input

### ISSUE THREAD

**Issue by ItsPierre** [TarekRaafat/autoComplete.js#121]
Is it possible to build an autocomplete, which works just like a select.
For example, if a user has selected an item and the value is written in the input field, but the search field is focused again, I want to display the result list as it would be without any query.
If the user then types, the search should function like it usually does.

**Comment by TarekRaafat** [comment]
Hello @ItsPierre,

If I got you right, then all you need to do is just clearing the `results_list` items on the `blur` event, and this should give you the result you're after.

The results list is going to be rendered again automatically on the set `trigger` event, as shown in this [example](https://codepen.io/tarekraafat/pen/KKVXObd?editors=0010).

Let me know if that was helpful enough or not.

Cheers! :)

**Comment by ItsPierre** [comment]
Hi @TarekRaafat 

Unfortunately I don't think, that is what I want to achieve. I want the autocomplete work just like a select, just with the ability to search. Here are a few examples in form of images:

This is the autocomplete, when search is triggered with no query, showing every result until the limit is reached:
![image](https://user-images.githubusercontent.com/32811389/86325227-02418a80-bc40-11ea-897e-db501b5b7681.png)

When writing into the input, the search will be triggered and the results will be limited and the search string will be highlighted:
![image](https://user-images.githubusercontent.com/32811389/86325432-4df43400-bc40-11ea-9474-75cd697b7a4b.png)

If I now select an item, the full name will be written into the search field. Thats all good. But if I now focus the search field again, the search will be triggered normally and only the one matching result is shown:
![image](https://user-images.githubusercontent.com/32811389/86325514-72501080-bc40-11ea-81ca-95093fef8a45.png)

What I want to happen is, that if an item is already selected and I refocus the search field, it should show all results like at the beginning but still highlight the text, even if the search string theoretically is given. The search string itself should be selected, so that the user can start writing to start a new search:
![Unbenannt-1](https://user-images.githubusercontent.com/32811389/86326052-69137380-bc41-11ea-8803-9bdf62133cc2.png)

I hope this explains my intention.

I thought, I could just take the instance of the autocomplete and trigger the search with a defined empty string with a function like `instance.startSearch('')`. With that way, I could bind an event listener to the onfocus of the search field and start the search manually. That's the way it is working with the jQuery-Autocomplete.

**Comment by indovsky** [comment]
@ItsPierre Hi, did you find a solution to this problem?

**Comment by ItsPierre** [comment]
> @ItsPierre Hi, did you find a solution to this problem?

No I did not, I think, that is not possible at the moment with autocomplete.js and it must be extented.
This was just a suggestion on how it could possibly be added.

**Comment by mujx** [comment]
@ItsPierre The solution is described on #83. You can use `maxResults` to control the size of the default list.

**Comment by TarekRaafat** [comment]
@ItsPierre @indovsky,

As @mujx thankfully mentioned, #83 should get you the results you're after, also check this [example](https://codepen.io/tarekraafat/pen/RwKQobg?editors=0010) as well it's the same solution just a slightly different implementation.

**Comment by TarekRaafat** [comment]
@ItsPierre @indovsky,

As @mujx thankfully mentioned, #83 should get you the results you're after, also check this [example](https://codepen.io/tarekraafat/pen/RwKQobg?editors=0010) as well it's the same solution just a slightly different implementation.

**Comment by ItsPierre** [comment]
> @ItsPierre @indovsky,
> 
> As @mujx thankfully mentioned, #83 should get you the results you're after, also check this [example](https://codepen.io/tarekraafat/pen/RwKQobg?editors=0010) as well it's the same solution just a slightly different implementation.

Just tried out, what was mentioned in #83.
I don't think, this is the solution to my problem.

I am not searching for a way to trigger the search, I am searching for a way with which query to trigger it.
I think, my problem would be solved if I was somehow able to manipulate the query in the trigger.condition function.
Since this function is called one triggered, I could set the query to "" which means that every possible result is shown, as if the input field was empty.
If I now start typing, the "real" query is searched with.

I want the autocomplete to work as it would be select field but with the ability to type and restrict.
If I have selected an option "Apple" and I retrigger the search by focusing it, I want to display all results so that the user could select Banana if he wanted to. At the moment I only get the results "Apple", "Applepie", etc.
