### ISSUE TITLE
Change transition, size and color

### ISSUE THREAD

**Issue by ocp1000** [TarekRaafat/autoComplete.js#123]
Hi,
Love your auto complete code! It's really amazing.
I was wondering what I need to configure in order to achieve the following:

1. Remove transition: I'd like to search box to remain constant in side and not grow/shrink based on mouse focus/click etc.
2. Change color: How do I change the search bar color?
3. Change placeholder color: Currently it's barely visible, I'd like to make it a solid visible color.

I tried to mess with the CSS in `codepen` but every value that I change didn't affect the search box.

**Comment by TarekRaafat** [comment]
Hello @ocp1000,

Thank you! I'm glad it came in handy for you.

Simply you could use a different style sheet other than the default one that comes with `autoComplete.js`, or you could just override any values in a separate CSS using `!important` 

Please, let me know if that was not helpful enough for you.

Cheers! :)

**Comment by ocp1000** [comment]
Hi @TarekRaafat , thanks for the reply.
Any chance you can give me an example on how to do it? I'm a CSS n00b.

**Comment by TarekRaafat** [comment]
Here you go, cheers! :)

Codepen [example](https://codepen.io/tarekraafat/pen/zYrQYQR?editors=0100)
