### ISSUE TITLE
Paginate with api

### ISSUE THREAD

**Issue by dmbehrouz** [TarekRaafat/autoComplete.js#125]
Hi
I want to call an api service for show result.In my service return total count of all result and maybe total count over that 20 result but my service only return 200 result in every call. I want use your library for paginate of my service. Does exist this feature in your library?

Thank you for your help

**Comment by folknor** [comment]
This is no problem. You can't do it directly in autoComplete.js but you just need a few additional variables to keep the state and some custom code.

https://github.com/TarekRaafat/autoComplete.js/issues/95#issuecomment-830598444 doesn't do exactly what you want, but you can hook those prev/next buttons to custom `fetch` code and do it manually.
