### ISSUE TITLE
Hide Results List on Blur

### ISSUE THREAD

**Issue by ckpicker** [TarekRaafat/autoComplete.js#126]
## Issue Description
Hello, I'm having an issue with the results list not hiding if a user doesn't select an option.  I thought maybe the `trigger` param might allow for this, but adding 'blur' to the event array doesn't seem to help.

## Example:
![Screen Recording 2020-07-21 at 04 00 24 PM](https://user-images.githubusercontent.com/173108/88101162-9af66680-cb6b-11ea-86f7-d191c82b8ca0.gif)

## JS Config:
```
  const autoCompletejs = new autoComplete({ // eslint-disable-line
    data: {
      async src() {
        // Fetch External Data Source
        const source = await fetch('us_institutions.json');
        const data = await source.json();
        // Returns Fetched data
        return data;
      },
      key: ['institution'],
      cache: true,
    },
    trigger: {
      event: ['input','blur'],
    },
    searchEngine: 'strict',
    highlight: true,
    selector: '.gf_auto_complete input',
    threshold: 3,
    debounce: 300,
    maxResults: 5,
    resultsList: {
      render: true,
    },
    onSelection(feedback) {
      // Add value
      document.querySelector('.gf_auto_complete input').value = feedback.selection.value.institution;
    },
  });
```

## Desired Behavior
I would like for the results list to hide when the focus of the `input` moves to another element.

**Comment by ckpicker** [comment]
I was able to resolve this by adding a `blur` event listener to the `input` field, and then calling this function:

```
const hideResultsList = () => {
  const autoCompleteList = document.getElementById('autoComplete_list');

  if (autoCompleteList) {
    autoCompleteList.innerHTML = '';
  }
};
```

It would still be nice to have access to [`clearResults`](https://github.com/TarekRaafat/autoComplete.js/blob/d8034016b5785b73d7682142c9d8f6d80736aad2/src/views/autoCompleteView.js#L78) so that this could be called programmatically.

**Comment by vandre** [comment]
I also had the same issue with the results list not hiding by default. Here is the pure CSS workaround I used with the OOB element IDs:

```
#autoComplete + ul#autoComplete_list{
  display:none;

}
#autoComplete:focus + ul#autoComplete_list {
  display: block;
}
```

**Comment by AzA-95** [comment]
My solution taken from demo

```
// Toggle event for js-delivery input
// showing & hidding results list onfocus / blur

["focus", "blur"].forEach(function (eventType) {
	const resultsList = document.querySelector("#autoComplete_list");

	inputEl.addEventListener(eventType, function () {
		if (eventType === "blur") {
			// Hide results list
			resultsList.style.display = "none";
		} else if (eventType === "focus") {
			// Show results list
			resultsList.style.display = "block";
		}
	});
});
```

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
