### ISSUE TITLE
Autocomplete doesn't work in OS X Safari

### ISSUE THREAD

**Issue by rodighiero** [TarekRaafat/autoComplete.js#128]
Autocomplete has some trouble I don't understand with Safari, while in Chrome it works perfectly well. I spent a few hours on that without seeing any solution. Help will be appreciated, thanks.

This is my webpage https://rodighiero.github.io/DH2020/
This is library implementation https://github.com/rodighiero/DH2020/blob/master/src/elements/search.js

**Comment by TarekRaafat** [comment]
Hello @rodighiero,

I've checked your nice webpage on safari, and I believe that there another javascript code that's preventing the user from typing inside the input field more than one character for some unknown reason, which I'm trying to figure out.

Something else I've noticed that's worth mentioning that when you change window focus and get back to your page, you get to write another single character.

I'm currently investigating your issue, and I'll let you know as soon as I find out any clue.


Have a nice day! :)

**Comment by rodighiero** [comment]
Thank you @TarekRaafat,

I took a look at the bundle, but it seems okay. I use just two libraries that should not affect any input listener. They are PIXI.js and d3.js. Please tell me if I can do further checks and keep me updated!

Have a nice day you too!

**Comment by rodighiero** [comment]
I've found the problem and it was not in the library. Safari needs to add this code in the CSS:

```
input, input:before, input:after {
	-webkit-user-select: initial;
	-khtml-user-select: initial;
	-moz-user-select: initial;
	-ms-user-select: initial;
	user-select: initial;
}
```

Thanks for helping me,
Dario

**Comment by TarekRaafat** [comment]
Interesting finding I've never came across it before.
I'm glad that you've found the solution at the end of the day.

Anytime, cheers! :)
