### ISSUE TITLE
Fire programatically with pre-filled value

### ISSUE THREAD

**Issue by fluxxus** [TarekRaafat/autoComplete.js#129]
Is there an option to search and display results with pre-filled value, without the need to type anything into input field?

Here is an example of what I need. 

```
// get autocomplete input
const siteUrlInput = document.querySelector('#autoComplete');
// get the search part of URL
const siteUrl = window.location.search.substring(1);
// assign the value to autocomplete
siteUrlInput.value = siteUrl;
```
After I assigned the value to `AutoComplete` input, I would like to get results for that query, but doing it programatically, without key presses etc.

Thanks

**Comment by TarekRaafat** [comment]
Hello @fluxxus,

Sure, you can do that after instantiating `autoComplete.js` as shown in the code below.

```js
// Get autocomplete input
const siteUrlInput = document.querySelector('#autoComplete');
// Get the search part of URL
const siteUrl = window.location.search.substring(1);
// Assign the value to autoComplete.js
siteUrlInput.value = siteUrl;

// New Input Event
const event = new Event('input', {
    bubbles: true,
    cancelable: true,
});
// Event Dispatcher
input.dispatchEvent(event);
```

Try it and let me know how it went.

Cheers! :)

**Comment by fluxxus** [comment]
Hi @TarekRaafat and thanks for the quick response!! :)

Just one more thing please. How should I access the results now.

This clearly is not working now `onSelection: feedback => {} `. Any alternative approaches to accessing the results?

**Comment by TarekRaafat** [comment]
Sorry, I didn't get your question.

Could you please clarify what you mean by accessing the results not working, because in this [demo](https://codepen.io/tarekraafat/pen/vYGLYRM?editors=0010) accessing the results list and navigation works fine.

**Comment by fluxxus** [comment]
Ok, I will try to explain better this time. 

I would like to have access to `feedback` without the need for user input. In your Codepen demo, I need to select one of the options to get the result displayed on the screen via `feedback.selection.value`.

Is there a way I can get the result displayed without the need for choosing anything? 

Or better yet, I see in the console that `CustomEvent` is available on page load. It contains all of the information I need for the given query. 

How can I access the info contained in that `CustomEvent`?

p.s. I hope I explained it better this time :)

**Comment by fluxxus** [comment]
Managed to do it on my own in the end. Thanks for the help! :)
