### ISSUE TITLE
Keyboard events do not bind if onSelection not defined

### ISSUE THREAD

**Issue by AustinGrey** [TarekRaafat/autoComplete.js#130]
- [ ] **System Information**
  - [ ] Firefox 79.0

- [ ] **Describe the bug**
If the onSelection key is not provided, the keyboard events for the up and down arrow keys do not bind to the input. So pressing the up and down arrow keys just jumps to the first and last letters instead of moving up and down the results list.

- [ ] **To Reproduce**
1. Create a new autocomplete like so
```
new autoComplete({
            data: {
                src: ['some', 'results'],
                cache: false
            },
            placeHolder: "Try me",
            highlight: true,
            resultsList: {
                render: true
            },
        })
```
2. Enter `res` and observe that 'results' shows as a suggestion
3. Try to navigate using arrow keys and enter
4. Observe nothing happens
5. Also observe in the DOM that no `keydown` event has been attached to the input

- [ ] **Expected behavior**
The up and down arrow keys/enter should work out of the box, and on Selection should be to provide additional logic.

**Comment by TarekRaafat** [comment]
Hello @AustinGrey,

Thank you for reporting this unusual behavior which is not intended.

I Will fix this bug asap.


Have a nice day, cheers! :)

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
