### ISSUE TITLE
Webpacker Example?

### ISSUE THREAD

**Issue by xrimpy** [TarekRaafat/autoComplete.js#136]
Library looks promising. 

I am a rails developer, and am not so fluent with JavaScript.

A simple multi instance example with WebPacker would highly be appreciated.

This might be a hindrance for a lot of developer discovering your library as they are unable to get started.

I am willing to put my time if you need any help.

In case I figure the WebPack code, I will contribute to the Wiki.

Thanks

**Comment by TarekRaafat** [comment]
Hello @xrimpy,

I'm not sure if you got you right... if you're referring to multiple instances on the same page you can check this #82, if not please clarify I'm already looking forward to your support, and I love your enthusiasm!

Have a good day! :)
