### ISSUE TITLE
Data load after user start typing

### ISSUE THREAD

**Issue by noreff** [TarekRaafat/autoComplete.js#138]
I noticed that by default data is fetched on page load. My data json file is ~300 kb which is a lot. Not all the users use search so I don't see why they should download this extra kbs which they will not use. I didn't found yet how to make data load when user start typing, not on page load. 

If it can be achieved with current codebase please let me know, if not can I make a PR for that?

**Comment by AzA-95** [comment]
You can in (data src) check field input to empty. For prevent send ajax with empty value

See my example of screen

![Снимок](https://user-images.githubusercontent.com/52655410/97307440-84a22a00-1881-11eb-9138-ce839713d294.PNG)
