### ISSUE TITLE
onSelection is triggered when the result lists has display: none attribute

### ISSUE THREAD

**Issue by markoboy** [TarekRaafat/autoComplete.js#139]
- [x] **System Information**
  - [x] Google Chrome v86
  - [x] Windows 10 pro
  - [x] Codepen
  - [x] No errors in the JS console

- [x] **Describe the bug**

When you search on the input field, after you blur from it by either going to a different program or clicking on the dev tools. The list gets a display none but when you click where the list would appear if it had display block, the onSelection callback is triggered.

- [x] **To Reproduce**
Steps to reproduce the behavior: <!-- Example below-!>
1. Go to https://codepen.io/markoboy/pen/jOrpayK
2. Open dev tools
3. Start a search
4. Click anywhere on the dev tools to trigger blur event
5. Click where the list would appear
6. The onSelection callback will be triggered

- [x] **Expected behavior**
The onSelection event to not be triggered when the list is hidden.

- [x] **Screenshots or GIF's (optional, but HIGHLY RECOMMENDED)**
![ezgif-7-03fd77510226](https://user-images.githubusercontent.com/35178536/98230738-68724d00-1f53-11eb-98a5-3f6dbc67f146.gif)

- [x] **Additional context (optional)**
The gif is a bit quick but you can view that the selection output changes when you click below the input field.

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
