### ISSUE TITLE
Get the first item from the result

### ISSUE THREAD

**Issue by mrahmadt** [TarekRaafat/autoComplete.js#140]
Hello

Is it possible to get the first item from the result list from outside autoComplete?

any guidance how to do that?

Thanks

**Comment by TarekRaafat** [comment]
Hello @mrahmadt,

I didn't get what you mean by getting the first result item from the result list from outside autoComplete.
Kindly provide more explanation on what you're trying to achieve for me to be able to support you.

**Comment by mrahmadt** [comment]
Hello Tarek

Here is what I mean:

```
document.querySelector("#autoComplete").addEventListener("keydown", event => {
	if(event.key === 'Enter') {
		console.log('og event:', event.currentTarget.value);   <--- Instead of the input text, I want to be able to get the first item from the result list
	}
});
```

**Comment by mrahmadt** [comment]
I think I found the solution for it from https://github.com/TarekRaafat/autoComplete.js/issues/52

Thanks Tarek for this amazing script

**Comment by TarekRaafat** [comment]
@mrahmadt I'm glad you found the solution!

Let me know if you need any support.

Cheers! :)
