### ISSUE TITLE
Release of v8

### ISSUE THREAD

**Issue by nhaberl** [TarekRaafat/autoComplete.js#141]
Hi, any news on the release of v8 ?

**Comment by TarekRaafat** [comment]
Hello @nhaberl,

[v8](https://github.com/TarekRaafat/autoComplete.js/tree/v8.0.0) is in the works already, and everything is going according to plan.

It will be released by end of this month.

Stay connected, cheers! :)

**Comment by nhaberl** [comment]
👀

**Comment by TarekRaafat** [comment]
Hello @nhaberl,

Thanks for your patience and for following up.

Here you go [v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0) enjoy and please let me know your feedback.

Have a nice day, cheers! :)
