### ISSUE TITLE
data.src calls before threshold

### ISSUE THREAD

**Issue by ETNyx** [TarekRaafat/autoComplete.js#142]
Hello,

```
new autoComplete({
    data: {                              // Data src [Array, Function, Async] | (REQUIRED)
      src: async () => {
        const query  = document.querySelector("#autoComplete").value;
        const source = await fetch("/search/?q=" + query);
        const data   = await source.json();
        return data;
      },
      key: ["title"],
      cache: false
    },
    selector: "#autoComplete",
    threshold: 2                        // Min. Chars length to start Engine | (Optional)
});
```

if you set "threshold" for 2, showing results is delayed until third char is set. I believe this should be also applied to calling data? Now, every keystroke autoComplete send XHR request even when it is not necessary, when threshold forbids showing results.

(Sure sure one can say, use "debounce" as human buffer, I also hotfix this by sending empty json and not searching database before threshold)

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
