### ISSUE TITLE
Resources not found

### ISSUE THREAD

**Issue by alexalannunes** [TarekRaafat/autoComplete.js#145]
Isn't necessary put system information.

When I go to the demo

![image](https://user-images.githubusercontent.com/16847836/101207636-abf1d100-364f-11eb-8d7e-20f8e2a39055.png)

**Comment by TarekRaafat** [comment]
Hello @alexalannunes, there was an issue with the build that has already been resolved now please check again and let me know how it went.

Cheers! :)

**Comment by alexalannunes** [comment]
@TarekRaafat All ok.
Thanks :smile: :tada:
