### ISSUE TITLE
Demo doesn't work in Chrome v87

### ISSUE THREAD

**Issue by momander** [TarekRaafat/autoComplete.js#146]
My system: Chrome v87 on MacOS 10.15.6.

The demo at https://tarekraafat.github.io/autoComplete.js/demo/ doesn't work in Chrome v87. The auto-complete box doesn't show any suggestions when I type into it.

The problem seems to be related to the MIME types of the served files, see attached screenshot.

![image](https://user-images.githubusercontent.com/499745/101207804-024a1a00-3626-11eb-9be5-576f4e4043cf.png)

**Comment by TarekRaafat** [comment]
Hello @momander, there was an issue with the build that has already been resolved now please check and let me know how it went.

Cheers! :)

**Comment by momander** [comment]
Thanks for looking into it. It's working for me now!
