### ISSUE TITLE
Highlighting single search terms based on word breaker

### ISSUE THREAD

**Issue by nhaberl** [TarekRaafat/autoComplete.js#147]
Hi, would be great to have the chance to control what words will be highlighted in the results.
I guess a Regex would be best.

This gives thebpossibility to highlight only prefix, postfix and single words found break by space (or whatever)

**Comment by TarekRaafat** [comment]
Hello @nhaberl,

Have you checked the `resultItem.content` API?
Based on my understanding I believe that the `resultItem.content` API shall let you achieve the results you're after.

Please, let me know if I didn't get you right.


Have a nice day, cheers! :)
