### ISSUE TITLE
Multiple init() calls are initiated by MutationObserver callback

### ISSUE THREAD

**Issue by stopdesign** [TarekRaafat/autoComplete.js#149]
In preInit you set the MutationObserver callback. It calls init() multiple times because mutationsList could have many MutationRecords. Some (all) of them could have inputField inside. For example, in my case I have 3 records:
<img width="549" alt="Screenshot 2020-12-08 at 18 22 21" src="https://user-images.githubusercontent.com/244666/101518609-710ad880-3982-11eb-9385-8b3ccc3c235d.png">

https://tarekraafat.github.io/autoComplete.js/demo/ is affected. I see 9 init() calls.

Affected versions: >= 8.0.0.

OSX, Chrome 87.0.4280.67, Safari Version 13.0.4.

To Reproduce: visit the [demo](https://tarekraafat.github.io/autoComplete.js/demo/), open debug console, type any character and look at number of generic.json requests you have. I have 9 for each keypress event.

Expected behavior:
1. Only one init() call.
2. Possibility to call init() manually (preInit approach is incompatible with onload() initialisation).

**Comment by TarekRaafat** [comment]
Hello @stopdesign,

The input field observer is already set to fire the `init()` function only one time after fulfilling the required condition which is the availability of the input field element, and then the observer disconnects automatically so it doesn't fire ever again as long as the input field exists.

I've tried reproducing the reported behavior on the same mentioned browsers, versions, and operating system but unfortunately couldn't get the same results as yours.

My initial assumption is that you might be using a class for the input selector or the same id maybe.

Please try to share any more details that might help in debugging that weird behavior.

I'm thinking about availing an API for the `observer` to be able to turn it on/off. What do you think about that?


Have a nice day, cheers! :)

**Comment by cedbesafilm** [comment]
@TarekRaafat i have the same problem (i opened the issue for the feature request #89)

Every event is triggered multiple time (include init), in my case 35

![image](https://user-images.githubusercontent.com/55377336/101638474-660d8200-3a2e-11eb-9eae-5357893e90ec.png)

**First Test**
![image](https://user-images.githubusercontent.com/55377336/101637544-3316be80-3a2d-11eb-883a-dc6f94f92b57.png)
![image](https://user-images.githubusercontent.com/55377336/101637503-24300c00-3a2d-11eb-89fa-7191f8828068.png)

**Second Test**
![image](https://user-images.githubusercontent.com/55377336/101638106-f26b7500-3a2d-11eb-89af-aa6b20f5000e.png)
![image](https://user-images.githubusercontent.com/55377336/101638212-14fd8e00-3a2e-11eb-8b3d-35bbcb3175d4.png)
and so on....

*Sorry for the quality of code but i wrote it in hurry for the issue* 😄

**Comment by TarekRaafat** [comment]
Hello @stopdesign and @cedbesafilm,

Thanks for your patience.

I have added a new API in [v8.1](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.1.0) that controls the `observer` by turning it `on/off` it's `off` by default.

Hope this is convenient for you for the time being until I fix this issue, awaiting your feedback.


Have a nice day, cheers! :)

**Comment by cedbesafilm** [comment]
With default settings now the problem it's solved for me 😄

**Comment by TarekRaafat** [comment]
@cedbesafilm that's great! I'm glad to hear that your problem is solved.

Please let me know if you need any further support.


Have a nice day, cheers! :)
