### ISSUE TITLE
resultsList destination does not work

### ISSUE THREAD

**Issue by RobinLawinsky** [TarekRaafat/autoComplete.js#150]
Hi, I have the following problem, 
I don't want to have the result list under the input tag.
The setting to append the "ResultList" to another element does not work 
and seems not to be implemented in version 8. Can you help me?

**Comment by TarekRaafat** [comment]
Hello @RobinLawinsky,

Good catch! I'm fixing it and will release the fix asap.

Thanks for reporting that.


Have a nice day, cheers! :)

**Comment by TarekRaafat** [comment]
[v8.0.3](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.3)

**Comment by RobinLawinsky** [comment]
@TarekRaafat thank you very much

**Comment by TarekRaafat** [comment]
@RobinLawinsky, anytime dear.

Have a nice day! :)
