### ISSUE TITLE
Example in Docs not Working

### ISSUE THREAD

**Issue by kanine** [TarekRaafat/autoComplete.js#156]
Using the latest 8.1.0 release I am unable to get the sample working from the docs. First off food2fork is no longer operating so I generated a JSON file that I believe matches the source as attached.

The button renders with the correct styling but nothing comes up when typing into the search box eg jala

[sample.txt](https://github.com/TarekRaafat/autoComplete.js/files/5686757/sample.txt)

Can you please review your document as it would be great to use this but right now it's not rendering correctly when following this example.

**Comment by TarekRaafat** [comment]
Hello @kanine,

Please share your `autoComplete.js` configuration if possible to be able to reproduce.

Cheers! :)

**Comment by kanine** [comment]
Hi,
Sorry for not getting back sooner, I wrote my own autocomplete but this is the example that doesn't work:

https://tarekraafat.github.io/autoComplete.js/#/?id=introduction
