### ISSUE TITLE
Autocomplete list open upwards when at the edge of the page

### ISSUE THREAD

**Issue by cedbesafilm** [TarekRaafat/autoComplete.js#158]
**Is your feature request related to a problem? Please describe.**
Now the autocomplete open downwards in evey situation, on mobile the user can not notice the list open

**Thoroughly Describe the solution you'd like**
if the autocomplete is open at the lower limit of the page the list should open upwards

**Please provide a few use cases for this feature**
1. on mobile the user can not notice the list open

**Please Describe alternatives you've considered**
For now i'm studing a custom method when list renders

**Additional context**
**current behavior**
![image](https://user-images.githubusercontent.com/55377336/102605667-e49caa80-4125-11eb-88ab-738ee08b88c2.png)

![image](https://user-images.githubusercontent.com/55377336/102605722-0007b580-4126-11eb-85db-28ba5b34726e.png)

**expected behavior**
*This is and example take from a Select*
![image](https://user-images.githubusercontent.com/55377336/102605848-35ac9e80-4126-11eb-8846-d58dd858fdf2.png)

**Comment by cedbesafilm** [comment]
## MY WORKAROUND
Pieces of code taken from [ChoicesJS](https://github.com/jshjohnson/Choices)


### Javascript
**I use rendered event because in resultsList the property bottom is always 0 (maybe is not injected in the DOM already?)**
```
      i.addEventListener("rendered", function() {
        var shouldFlip = false;
        var el = document.getElementById("autoComplete_list");
        var dropdownPos = el.getBoundingClientRect().bottom
        
        shouldFlip = !window.matchMedia("(min-height: " + (dropdownPos + 1) + "px)").matches;

        if (shouldFlip) {
          el.classList.add("is-flipped");
        }
      }, false);
```

### CSS
```
#autoComplete_list.is-flipped {
  top: auto;
  bottom: 100%;
  margin-bottom: 0rem;
}
```
### VISUAL
**On lower edge**
![image](https://user-images.githubusercontent.com/55377336/102611027-7d372880-412e-11eb-9727-9a6cdb6d15e3.png)

**Normal behavior**
![image](https://user-images.githubusercontent.com/55377336/102611078-8e803500-412e-11eb-9316-02bff7472f1d.png)

**Comment by mits87** [comment]
Also I have the same problem. Would be good if the plugin will support that out of the box

**Comment by edj56** [comment]
Hello :) Yes, it would be great to have this feature, please take a look

**Comment by amiregelz** [comment]
@TarekRaafat Is there a way to always open the dropdown upwards? trying to figure out what CSS to apply
