### ISSUE TITLE
Refresh data on selection

### ISSUE THREAD

**Issue by angelkw** [TarekRaafat/autoComplete.js#159]
I am adding this type ahead feature to a larger search widget with many other options. When a user selects (onselection) I am making an ajax call to update the data for the entire widget (disabling items that are no longer useful depending on what the user searches). Is there a way to re-instantiate the data set with the results from this ajax call for the type ahead from this ajax call on selection? Right now, the data set from the initial page load init stays even after the user makes a selection.
Thank you for any advice.

**Comment by TarekRaafat** [comment]
Hello @angelkw,

Apologize for my late reply.

If I got your point right you could easily turn off `data.cache: false` to make sure that on each `trigger` the data gets refreshed.

Please try it and let me know how it goes.

Have a nice day! :)
