### ISSUE TITLE
Selector does not accept a function

### ISSUE THREAD

**Issue by goaround** [TarekRaafat/autoComplete.js#160]
**Describe the bug**

The API documentation says that the selector can be a String e.g. id / class or a function e.g. `( ) => document.querySelector("")`

But the selector only acceps a string otherwise `Uncaught DOMException: Document.querySelector: '[object HTMLInputElement]' is not a valid selector`

See https://github.com/TarekRaafat/autoComplete.js/blob/1a0352f97dd4828358415a88cca387b9db029897/src/autoComplete.js#L181

`this.inputField = document.querySelector(this.selector);`

**To Reproduce**
Try to set the selector as a function e.g. `selector: () => document.querySelector("#autoComplete")`

**Expected behavior**

`this.inputField = typeof this.selector === 'string' ? document.querySelector(this.selector) : this.selector();`

**Comment by goaround** [comment]
PR: https://github.com/TarekRaafat/autoComplete.js/pull/161

Found one more: resultsList.destination can be also a function: https://github.com/TarekRaafat/autoComplete.js/pull/162

**Comment by TarekRaafat** [comment]
Hello @goaround,

Very Good catch!

Thanks for fixing them, and here is the fixed version [v8.1.1](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.1.1).


Have a nice day, cheers! :)
