### ISSUE TITLE
resultList 'data' does not contain 'match' per the docs

### ISSUE THREAD

**Issue by jwendel** [TarekRaafat/autoComplete.js#163]
From the documentation: https://tarekraafat.github.io/autoComplete.js/#/?id=api-configuration, the `resultItem` has the line:

```
1- content:
- Function (data, source) => { ... }
- data.match has to be used for Highlighted result
```
But looking at the latest code that ends up calling the resultItem function, I see: https://github.com/TarekRaafat/autoComplete.js/blob/master/src/components/Item.js#L16-L17
It looks like resultItem is only being passed `item.value`, when it really should be passed `item`.

**Comment by TarekRaafat** [comment]
Hello @jwendel,

Good catch!

You're totally correct thanks.
Here is the fix [v8.2](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.2.0)


Have a nice day, cheers! :)
