### ISSUE TITLE
[question] Live-reload changes to static data src

### ISSUE THREAD

**Issue by caycaycarly** [TarekRaafat/autoComplete.js#170]
How to live-reload the changes to the static data src like the one used in the live demo?

**Comment by TarekRaafat** [comment]
Hello @caycaycarly,

Could you please clarify more what you mean?

**Comment by caycaycarly** [comment]
Apologies.

So now, just like how the demo website's data src is a .json file, my use case similar, just that it will require arbitrarily overwriting the file every couple of weeks. I've noticed issues related to data src refreshing and code mentioning "livereload", and I assumed this was JS code to detect changes to the arc and reindex it.

So, I was wondering if live-reloading the data, without having to restart the http server is something that exists/ can be baked in autoComplete.js or would I need to implement another JS/bash solution for the same.

**Comment by TarekRaafat** [comment]
No worries at all :)

The issues you're referring to are mostly about the "livereload" development code that existed in the build version by mistake and had to be removed, but there is not "livereload" function built-in `autoComplete.js`.

Regarding your second point, if I got you properly I believe in your case you wont need to restart the server or have a live reload function with `autoComplete.js` for each time you update your `.json` file as long as you refresh the page that has the `autoComplete.js`.


Please let me know if I've answered your questions.

**Comment by caycaycarly** [comment]
Ah. That did answer my question. Thank you.
