### ISSUE TITLE
Spaces are converted into &nbsp;

### ISSUE THREAD

**Issue by mufaddalmw** [TarekRaafat/autoComplete.js#178]
@TarekRaafat  inside autocomplete dropdown results, all the spaces between words getting converted into `&nbsp;` is this known issue? because of this behavior words doesn't break into the next line. 
![Screenshot](https://user-images.githubusercontent.com/1768671/106598919-d4c01500-6571-11eb-8f86-6c1cf336df10.png)

**Comment by TarekRaafat** [comment]
Hello @mufaddalmw,

I've checked the [demo](https://tarekraafat.github.io/autoComplete.js/demo/) and found empty spaces but were not converted into `&nbsp;` and without any line breaks as well.

<img width="433" alt="Screen Shot 2021-02-02 at 7 00 00 PM" src="https://user-images.githubusercontent.com/3501930/106635147-2c1daf80-6589-11eb-910a-855674bb295f.png">


If you could help me replicating your issue that would be great! :)
