### ISSUE TITLE
Selector as a function breaks when mutation is true

### ISSUE THREAD

**Issue by brunobg** [TarekRaafat/autoComplete.js#179]
Try to open autocomplete with `observer: true` and `selector: () => document.querySelector('#xxx')`. It explodes:

```
Uncaught DOMException: Document.querySelector: 'function selector() {
        return document.querySelector("#xxxxx");
      }' is not a valid selector autoComplete.js:587
    callback autoComplete.js:587
    (Async: MutationCallback)
    preInit autoComplete.js:605
    autoComplete autoComplete.js:488
```

Seem to be linked to https://github.com/TarekRaafat/autoComplete.js/issues/160

This is the culprit:

https://github.com/TarekRaafat/autoComplete.js/blob/da042b278692bff22cf19724120d7a806346aa27/src/autoComplete.js#L218

**Comment by TarekRaafat** [comment]
Hello @brunobg,

Good catch man!

I've just tested the `selector` as a function with the `observer` on, and you're correct I've got the exact same error.

You're totally right the observer `inputField` selector is the cause.

I'll fix it tomorrow and update you as soon as I'm done.


Have a nice day, cheers! :)

**Comment by TarekRaafat** [comment]
[v8.3.2](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.3.2)
