### ISSUE TITLE
How can I re assign new data source to a auto complete

### ISSUE THREAD

**Issue by albu77** [TarekRaafat/autoComplete.js#18]
I'm making some progress but still ask myself a lot of questions:
I would like to use autocomplete in a sort of manufacturers/products choice (like that but it's a small private project...)

1. First I thought I could use two autocomplete but I don't think, after what I understood that is possible.

2. Second I thought to modify the data source of the only one autocomplete .

**Desired Process description:**

- The user type in some letters of a manufacturer the list display differnt choices
- The user select one
- The user click on next : the program change the auto complete  data source, key  and feedback to allow the user to type a product
- The autocomplete is fed with products and display a selection
- The user select one and eventually get a compet manufacturer/product choice.

Would you have any advice.

**Comment by TarekRaafat** [comment]
From what I've understood, what you're after could be achieved by `autoComplete.js` as follows.

> You just create two different `Input` fields with different IDs and two `autoComplete.js` instances for them.

#### Input 1
```html
<input id="manufacturers">
```

#### Input 2
```html
<input id="products">
```

#### Javascript
```js
const manufacturers = new autoComplete({            // First Instance
    data: { src: data, key: "manufacturers" },      // (Array, Object, Function, Async)
    placeHolder: "Manufacturers...",                // Place Holder text
    selector: "#manufacturers",                     // Input field selector
    threshold: 0,                                   // Min. Chars length to start
    searchEngine: "strict",                         // Search Engine type/mode
    renderResults: {                                // Rendered results Destination & position
        destination: document.querySelector("#manufacturers"),
        position: "afterend"
    },
    highlight: true,                                // Highlight matching results
    maxResults: 5,                                  // Max. number of rendered results
    onSelection: feedback => {                      // Action script on Manufacturer selection
        console.log(feedback);

        const products = new autoComplete({                 // Second Instance
            data: { src: feedback.selection.products, key: "products" }, // (Selection products array)
            placeHolder: "Products...",                     // Place Holder text
            selector: "#products",                          // Input field selector
            threshold: 0,                                   // Min. Chars length to start
            searchEngine: "strict",                         // Search Engine type/mode
            renderResults: {                                // Rendered results Destination & position
                destination: document.querySelector("#products"),
                position: "afterend"
            },
            highlight: true,                                // Highlight matching results
            maxResults: 5,                                  // Max. number of rendered results
            onSelection: feedback => {                      // Action script on Product selection
               console.log(feedback);
            }
        });

    }
});
``` 

> And of course the `Products` input field will just be visible after the `Manufacturer` selection.

Hope that's helpful

**Comment by albu77** [comment]
Many thanks, I've tried before several instances but I'd probably made errors in my code.
I will work on that and try to not bother you anymore for this. Have a good day

**Comment by TarekRaafat** [comment]
@albu77 You're welcome, if you would like to share your code over ([JSFiddle](https://jsfiddle.net/), [JS bin](http://jsbin.com), [Codepen](https://codepen.io/)) and we can review it together.

I’m glad to help you can bother me any time, just let me know how it went with my above suggestion.

Have a good day too! :)

**Comment by albu77** [comment]
![image](https://user-images.githubusercontent.com/624802/50737791-6f9c6880-11cd-11e9-870b-e29e7340334e.png)

**Comment by TarekRaafat** [comment]
I agree with you I will make sure to update the documentation with multi-instances usage.

Check out the new release [v.3.0.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v3.0.0) or [CDN](https://www.jsdelivr.com/package/gh/TarekRaafat/autoComplete.js), it has an new `API` for the rendered result item control and customization. You can use it to assign custom classes as in the below example

```js
resultItem: (data, source) => {
    source.classList.add("manufacturers");
    return `${data.match}`;
},
```

Good luck with your app, i'm glad that autoComplete.js is fitting well in your app. Bootstrap was not used at all or any external library.

Try the above example with the new version and let me know how it went.

**Comment by TarekRaafat** [comment]
<img src="https://user-images.githubusercontent.com/624802/50737791-6f9c6880-11cd-11e9-870b-e29e7340334e.png">

> This one needs a treatment, let me get back to you on it.

**Comment by TarekRaafat** [comment]
@albu77 check out [v3.1.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v3.1.0) or [CDN](https://cdn.jsdelivr.net/gh/TarekRaafat/autoComplete.js@3.1.0/dist/js/autoComplete.min.js), I've added an `API` for the rendered results list `resultsList` control and customization. You can use it to assign custom classes as in the below example

```js
resultsList: {
  container: source => {
    source.classList.add("manufacturers_List");
  };
}
```

This should help.

**Comment by albu77** [comment]
I've tried with the modification above (the one I wrote changing the `id `of `resultsList`.....
But there is another problem since to my sens `resultsList `is common to both instances.....
So the result are always on the same side (here under "Vins" autocomplete)
![image](https://user-images.githubusercontent.com/624802/50740933-c8342b80-11f6-11e9-9de7-8d364d85dfa6.png)

![image](https://user-images.githubusercontent.com/624802/50740926-ae92e400-11f6-11e9-99ce-0a13a0293438.png)

**Comment by TarekRaafat** [comment]
@albu77 check out [v3.2.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v3.2.0) or [CDN](https://www.jsdelivr.com/package/gh/TarekRaafat/autoComplete.js), I've modified the code now you can return `String` of the `id` you want to assign for the results list container as shown below.

```js
resultsList: {
  container: source => {
    resultsListID = "manufacturers_List";
    return resultsListID;
  };
}
```

**Comment by albu77** [comment]
I've tried but still have the result only in one the list (the right one) even if they have differnt id now. I send you my simple test for double instances the data are coming from local object variables.
[AutoComplete3.2DoubleInstances.zip](https://github.com/TarekRaafat/autoComplete.js/files/2733186/AutoComplete3.2DoubleInstances.zip)

**Comment by albu77** [comment]
Ok that was what I meant two messages above with "But there is another problem since to my sens resultsList is common to both instances.....".
Besides, a point I would like to know: is it possible actually to add a css class to render differently some li of the ul in the results list ?.
I would like to put some different color or an icon depending of the value of a key in the data (here Color), for example
`var lesVins = [{"Vin":"Vougeot Blanc Clos du Prieuré","Producteur":"Vougeraie","**Color":"red"**},{"Vin":"Vougeot 1er cru Le Clos Blanc","Producteur":"Vougeraie","**Color":"white**" .......`

To my sense, in the actual version it is not possible, but perhaps a modification could be done in the function addResultsToList ...?

**Comment by albu77** [comment]
I've tried with a modification in your Code
   `result.setAttribute("class", select.result+" "+dataSrc[record].source["Color"]);`
![image](https://user-images.githubusercontent.com/624802/50808829-b2129200-1300-11e9-9920-60fd3db2e0d4.png)

But I don't understand enough to be able to set in the config a class to the li related to a key in the data...

**Comment by TarekRaafat** [comment]
@albu77 try out [v3.2.1](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v3.2.1) or [CDN](https://www.jsdelivr.com/package/gh/TarekRaafat/autoComplete.js?path=dist%2Fjs), i've isolated the `resultsList` value to allow multiple instances and tested it with your sample code and it worked perfectly fine.

Regarding the capability of customizing the `li` element of each result or adding classes, exits already as shown below.

```js
resultItem: (data, source) => {
    source.classList.add(data.source.color);
    return `${data.match}`;
}
```

**Comment by albu77** [comment]
Yes....
It's working fine for the two instances and the li item color .
Thanks and have a good day

**Comment by TarekRaafat** [comment]
Great!
Glad to hear that everything is working fine with you and good luck with your app.
Anytime, you too have a good day.
