### ISSUE TITLE
doesn't persist the input type, always changes input to type=text

### ISSUE THREAD

**Issue by adardesign** [TarekRaafat/autoComplete.js#180]
Was there any reason that the code changes the input type to text?

Type search comes with native styles and features (like clear button)

![image](https://user-images.githubusercontent.com/23543/108430119-e14d9a00-720e-11eb-9239-9562594bca3e.png)

[Here is the line in the source that changes the type](https://github.com/TarekRaafat/autoComplete.js/blob/8bedef1f8c0650a01ef288c7f907f775bde9de85/src/components/Input.js#L9)

**Comment by TarekRaafat** [comment]
Hello @adardesign,

Good point.

So, what do you suggest shall we change the input type to be `search` instead of `text` or just remove it and leave it open to personal preferences?

Cheers, have a nice day! :)

**Comment by adardesign** [comment]
I'd suggest leaving it open to personal preferences

Thanks!

**Comment by adardesign** [comment]
https://github.com/adardesign/autoComplete.js/pull/1
