### ISSUE TITLE
Adding an onClose event

### ISSUE THREAD

**Issue by yliharma** [TarekRaafat/autoComplete.js#188]
The input field in my use case is initially hidden and its visibility is triggered with a button.
When I do a research and then click outside the input, the result list is removed but I don't know how to reset the input to its initial hidden state.

It would be perfect if the `closeAllLists` function dispatched an event that one could catch.
```
import { closeAllLists } from "./listController";
```

**Comment by TarekRaafat** [comment]
Hello @yliharma,

Good one, I'll make sure to include a solution for your use case in the coming version since it makes a lot of sense.


Cheers, and have a nice day! :)

**Comment by TarekRaafat** [comment]
`close` event has been added to [v9.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v9.0.0) check the [docs](https://tarekraafat.github.io/autoComplete.js/#/configuration?id=close) for details.
