### ISSUE TITLE
Add config option for what should happen when enter is pressed

### ISSUE THREAD

**Issue by nornes** [TarekRaafat/autoComplete.js#189]
We are using the autocomplete on a search input which should present the user with options (links) and submit to the search page when enter is pressed. Because of the solution to #104 this doesn't work. 

I suggest a config option that lets the developer choose if default form action should run on enter or not. That would (hopefully) make everyone happy :) It could be as simple as a boolean in the config and would help us a lot! Now we have to do manual checks outside the autocomplete which feel hacky.

**Comment by TarekRaafat** [comment]
Hello @nornes,

Thanks for sharing your use case.

I've already implemented a solution for your use case and it will be released in the upcoming version.

Cheers, and have a nice day! :)

**Comment by TarekRaafat** [comment]
Using [v9.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v9.0.0) you can use the below code snippet to get the results you want to achieve.

```js
trigger: {
  event: ["keydown"],
  condition: (event) => {
    return event.key === "Enter";
  }
}
```
Here is a live [example](https://codepen.io/tarekraafat/pen/eYgVdrx?editors=0010) of this solution as well.

Please try it and let me know how it goes.
