### ISSUE TITLE
Configuration is not passed to listMatchingResults

### ISSUE THREAD

**Issue by aarongerig** [TarekRaafat/autoComplete.js#196]
**System Information**
- Any browser / any OS / any Node version

**Bug Description**
The configuration is never passed (see [here](https://github.com/TarekRaafat/autoComplete.js/blob/master/src/autoComplete.js#L133-L134)) to the method `listMatchingResults()`. However it is using the `config` parameter a couple of times. For example, if you want to define a custom highlight class name, this will never be applied to the highlight element.

```js
new Autocomplete({
  highlight: {
    render: true,
    className: 'my-highlight-class'
  }
})
```

This configuration still results in the default behavior, even though it shouldn't:
```html
This is some <span class="autoComplete_highlighted">text</span>
```

**Reproduction steps**
Follow the steps described above. Same goes for configurations: [`diacritics`](https://github.com/TarekRaafat/autoComplete.js/blob/master/src/services/search.js#L16) and [`searchEngine`](https://github.com/TarekRaafat/autoComplete.js/blob/master/src/services/search.js#L24)

**Expected behavior**
The configuration is passed to the method and taken into consideration, when using the default search engine implementation.

**Comment by TarekRaafat** [comment]
Hello @aarongerig,

Which version of `autoComplete.js` are you using?

**Comment by aarongerig** [comment]
Version 8.3.2

**Comment by TarekRaafat** [comment]
That's why the `className` for the `highlight` method won't work because it's part of the upcoming version `v9` not the current version `v8`.

The new `v9` should be ready to be released this weekend and you'll be able to use this feature.

**Comment by aarongerig** [comment]
Awesome, thank you!
