### ISSUE TITLE
Results returning in lowercase

### ISSUE THREAD

**Issue by nickbp12** [TarekRaafat/autoComplete.js#20]
Hello Tarek,

Not too sure if it's an issue, but it's a bit annoying.
I have a few products on my website called "BASIC", but they get returned like "basic", I am not too sure why that happens, I've ran through your code, and i think it has something to do with line 216-221, where you do this:
`var match = _this.search(inputValue, record[_this.data.key] || record);
if (match) {
    resList.push({
               match: match,
               source: record
    });
}`
But I am really not sure.

- Nick

**Comment by TarekRaafat** [comment]
Hello @nickbp12,

I knew about this behavior, but never thought that it would be annoying.

I agree with you that it would be better if the results are rendered in `resultsList` without normalising the data.

I'm working currently on an enhancements for it and it will be coming out in the next release.

Cheers! :)

**Comment by lekkerduidelijk** [comment]
I'm running into exactly the same issue here. Hope you can provide a fix for this. `text-transform: capitalize` doesn't quite cut it for me 😸

**Comment by nickbp12** [comment]
Hi Tarek,

That sounds good, I am looking forward to the next release!

Cheers :)

**Comment by TarekRaafat** [comment]
Hello @nickbp12 & @lekkerduidelijk 

Check out [v4.0.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v4.0.0) or [CDN](https://cdn.jsdelivr.net/gh/TarekRaafat/autoComplete.js@4.0.0/dist/js/autoComplete.min.js) it's just released and it supports rendering results in their original case as requested, here is the [demo](https://tarekraafat.github.io/autoComplete.js/demo/) & [release notes](https://tarekraafat.github.io/autoComplete.js/#/releases?id=release-notes).

Let me know your feedback.

Cheers! :)

**Comment by nickbp12** [comment]
Hello @TarekRaafat,

So I got around to trying it out, and I'm glad it's returning the results in the original case.

I do have one issue, if I type "a" it will for example return "Auto" 8 times. I have no idea why it does that.
I have changed the code myself to 
```
var getSelection = function getSelection(field, resultsList, callback, resultsValues) {
        var results = resultsList.querySelectorAll(".".concat(select.result));
        for (var i = 0; i < results.length; i++) {
            ["mousedown", "keyup"].forEach(function (eventType) {
                console.log(resultsValues);
                results[i].addEventListener(eventType, function (event) {
                    if (eventType === "mousedown" || event.keyCode === 13) {
                        console.log(resultsValues.matches);
                        callback({
                            event: event,
                            query: getInput(field).value,
                            matches: resultsValues.matches,
                            results: resultsValues.list.map(function (record) {
                                return record.value;
                            }),
                            selection: resultsValues.filter(function (value) {
                                var resValue = value.value[value.key] || value.value;
                                return resValue === event.target.closest(".".concat(select.result)).getAttribute(dataAttribute);
                            })[0].value
                        });
                        clearResults(resultsList);
                    }
                });
            });
        }
    };```

Changing this code to the new code you've made, doesn't fix it either, so I am not sure what's wrong.

Would you have time to look into why it returns 8 of the same result?

Thanks.
- Nick

**Comment by TarekRaafat** [comment]
Hello @nickbp12,

I've noticed that behavior too and i'm investigating it right now, will get back to you as soon as I find a solution for it.

Cheers! :)

**Comment by TarekRaafat** [comment]
Hello @nickbp12 it should be fixed by now, kindly check and let me know.

Check the new release as well [v5.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v5.0.0), [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js) & [CDN](https://www.jsdelivr.com/package/gh/TarekRaafat/autoComplete.js).
