### ISSUE TITLE
Option to have tab not be used to navigate results

### ISSUE THREAD

**Issue by codyjames** [TarekRaafat/autoComplete.js#202]
**Is your feature request related to a problem? Please describe.**
I think it'd be great if we could have tab not interact with the autocomplete results as it breaks default functionality. 

Adam Silver wrote about this here: https://adamsilver.io/blog/building-an-accessible-autocomplete-control/#composite-controls-should-have-a-single-tab-stop

**Thoroughly Describe the solution you'd like**
I'd love to have a way to pick which keyboard events work within the results. Currently it allows for arrows and tab. I'd love to be able to just allow arrows.

**Please Describe alternatives you've considered**
I see no alternatives.

**Additional context**
> A primary keyboard navigation convention common across all platforms is that the tab and shift+tab keys move focus from one UI component to another while other keys, primarily the arrow keys, move focus inside of components that include multiple focusable elements. The path that the focus follows when pressing the tab key is known as the tab sequence or tab ring.

**Comment by TarekRaafat** [comment]
Hello @codyjames,

@ronmichael opened a previous [discussion](https://github.com/TarekRaafat/autoComplete.js/discussions/175) about the same topic, and we've decided to park it for a while until we find that it's highly demanded "gets votes" before changing it not to impact other users.

So, let's remove it from the next major release.


Have a nice day! :)

**Comment by TarekRaafat** [comment]
Covered in [v9.0.1](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v9.0.1)
