### ISSUE TITLE
Sorting post code results based on first number.

### ISSUE THREAD

**Issue by AllenXavier** [TarekRaafat/autoComplete.js#203]
Hi, 

I am using your autocomplete library to autocomplete postal codes.
This is working so far, however. I would like it to show the results based on the first matching number.

Right now if I type in a 9, i get the first results containing a 9 not the results starting with a 9.

It is giving me this:
<img width="339" alt="Screenshot 2021-04-14 at 16 38 14" src="https://user-images.githubusercontent.com/44436430/114728959-d95a3400-9d3f-11eb-9958-c55ab01693ff.png">

Instead of the 9000 numbers first:
<img width="317" alt="Screenshot 2021-04-14 at 16 38 19" src="https://user-images.githubusercontent.com/44436430/114729070-f131b800-9d3f-11eb-80ff-608201c4942f.png">

Is this a possibility with your library?

regards,

**Comment by TarekRaafat** [comment]
Hello @AllenXavier,

Yes, you can achieve that using the [`data.results`](https://tarekraafat.github.io/autoComplete.js/#/configuration?id=data-required) API to sort the results according to your own criteria before rendering the list as shown below.

```js
results: (list) => {
  const value = document.querySelector("#autoComplete").value.slice(0, 1);
    // Sort results by starting character
    const sortedList = list.sort((a, b) => {
      if (!a.match.startsWith(value)) return -1;
      if (a.match.startsWith(value)) return 1;
      return 0;
    });
  // Return sorted list
  return sortedList;
}
```
<img width="398" alt="Screen Shot 2021-04-15 at 8 56 11 AM" src="https://user-images.githubusercontent.com/3501930/114827391-e96a2600-9dc8-11eb-93fd-45096783f64b.png">

Try it and let me know how it goes.

Have a nice day! :)

**Comment by jsunsawyer** [comment]
@TarekRaafat Thanks for this. Though there is an error with your results code. We got this working by reversing your return values for the startsWith checks.

Here's an updated version with the addition of making results case insensitive.
Note that `threshold` is a variable (`3` in our case) that matches our `threshold` setting.

```
results: (list) => {
  const value = (this.fieldTarget.value.slice(0, threshold)).toLowerCase();
  // Sort results by starting character
  const sortedList = list.sort((a, b) => {
    const listItemValue = a.value.title.toLowerCase();
    if (!listItemValue.startsWith(value)) return 1;
    if (listItemValue.startsWith(value)) return -1;
    return 0;
  });
  // Return sorted list
  return sortedList;
},
```

**Comment by TarekRaafat** [comment]
Hello @jsunsawyer,

Thanks for the correction much appreciated.

Cheers, and have a nice day! :)
