### ISSUE TITLE
feature request, multi key for search in object

### ISSUE THREAD

**Issue by Johann-S** [TarekRaafat/autoComplete.js#21]
Hi,

Thanks for that awesome plugin !

I would like to know what do you think about adding multi `key`s when we use an array of Objects.

For example:
```js
const data = [
	{ label: 'test', code: '0123456789' },
	{ label: 'test2', code: '9876543210' },
]
```

and key would be: `[ 'label', 'code' ]`

I'm sorry if it's not clear but do not hesitate to ask me more details

**Comment by TarekRaafat** [comment]
Hello @Johann-S ,

Check out [v4.0.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v4.0.0) or [CDN](https://cdn.jsdelivr.net/gh/TarekRaafat/autoComplete.js@4.0.0/dist/js/autoComplete.min.js) it's just released and it supports `Multiple` key search as requested, here is the [Codepen](https://codepen.io/tarekraafat/pen/rQopdW) & [release notes](https://tarekraafat.github.io/autoComplete.js/#/releases?id=release-notes).

Let me know your feedback.

Cheers! :)

**Comment by Johann-S** [comment]
Oh awesome ! thank you ❤️

**Comment by KrisPetkov** [comment]
Is it possible to display both results on the same line and both to have the match highlighted?
1. If have the following object:
`{ "name": "test", "description": "another test"}`
2. Our **key** property is:
`["name", "description"]`
3. How to make both highlighted whenever there is a match ❓ 
`resultItem: (data, source) => {
      return '${data.value.name} - ${data.value.description}';
}`

**This will just display them side by side separated with dash but will not highlight them**

**Comment by TarekRaafat** [comment]
Hello @KrisPetkov,

Sorry for my late reply.

In order to achieve such a result, you'll need to get the user's query to be compared against the matching result string and highlight it as shown in the below code snippet.

```js
resultItem: {
    content: (data, source) => {
       // Get query vallue
       let query = document.querySelector("#autoComplete").value;
       // Build desired result string
       const result = `${data.value.food} - ${data.value.cities}`;
       // Regular Expression Query Pattern Ignores caseSensitive
       const pattern = new RegExp(`${query}`, "i");
       // Search for a match Query in Record
       query = pattern.exec(result);
       // Returns the highlighted match					
       source.innerHTML = result.replace(query, `<span style="color: red;">${query}</span>`);
    },
    element: "li"
}
```

Please try it and let me know the results.

Stay safe, cheers! :)

**Comment by KrisPetkov** [comment]
@TarekRaafat  Thank you! great answer!

One more question? Is it possible to make the engine to color more than one word?
What I mean if I have the word "test" in **data.value.food** and in **data.value.cities** to color the word in both phrases simultaneously? 

Example (from your previous answer): `test` food name - some `test` city

**Comment by kasperkamperman** [comment]
I was looking to solve this problem by looking the issues. I think the API changed, right?
(Maybe others run into this when solving an issue like this, hence my comment). 

So instead of 
```
resultItem: {
  content: (data, source) => {
  }
}

```

We have to use:
```
resultItem: {
 element: (item, data) => {
 }
}
```

At least like the last one I could modify the element, the other option didn't work anymore. 
https://tarekraafat.github.io/autoComplete.js/#/configuration?id=resultitem-optional

**Comment by TarekRaafat** [comment]
Thanks @kasperkamperman, for your helpful comment! :)

> At least like the last one I could modify the element, the other option didn't work anymore.
> https://tarekraafat.github.io/autoComplete.js/#/configuration?id=resultitem-optional

Would you please clarify which option you are referring to?

**Comment by kasperkamperman** [comment]
I meant that "content: (data, source)" like mentioned in this topic didn't work anymore. 
But this worked "element: (item, data) => {"

So the full-code you showed in this topic would become in the most recent version (10.2.5) that I'm using:

```
resultItem: {
   element: (item, data) => {
       // Get query value
       let query = document.querySelector("#autoComplete").value;
       // Build desired result string
       const result = `${data.value.food} - ${data.value.cities}`;
       // Regular Expression Query Pattern Ignores caseSensitive
       const pattern = new RegExp(`${query}`, "i");
       // Search for a match Query in Record
       query = pattern.exec(result);
       // Returns the highlighted match					
       item.innerHTML = result.replace(query, `<span style="color: red;">${query}</span>`);
    },
    element: "li"
}

```

@TarekRaafat Thanks for the script and helpful replies.

**Comment by TarekRaafat** [comment]
Just a slight correction

```js
resultItem: {
   // For element tag type use `tag` instead of `element`
   tag: "li",
   // For the element itself use `element` instead of `content`
   element: (item, data) => {
       // Get query value
       let query = document.querySelector("#autoComplete").value;
       // Build desired result string
       const result = `${data.value.food} - ${data.value.cities}`;
       // Regular Expression Query Pattern Ignores caseSensitive
       const pattern = new RegExp(`${query}`, "i");
       // Search for a match Query in Record
       query = pattern.exec(result);
       // Returns the highlighted match					
       item.innerHTML = result.replace(query, `<span style="color: red;">${query}</span>`);
    }
}
```

Cheers, and have a nice day! :)

**Comment by devcer** [comment]
I needed something like this for both name and email search. I had to use replaceAll instead to highlight both email and name.

```
resultItem: {
   // For element tag type use `tag` instead of `element`
   tag: "li",
   // For the element itself use `element` instead of `content`
   element: (item, data) => {
       // Get query value
       let query = document.querySelector("#autoComplete").value;
       // Build desired result string
       const result = `${data.value.name} - ${data.value.email}`;
       // Regular Expression Query Pattern Ignores caseSensitive
       const pattern = new RegExp(`${query}`, 'ig');
       // Search for a match Query in Record
       // Returns the highlighted match
        item.innerHTML = result.replaceAll(
          pattern,
          `<span style="color: red;">${query}</span>`
        );
    }
}

```
