### ISSUE TITLE
Accept dom element as an alternative to selector

### ISSUE THREAD

**Issue by snimavat** [TarekRaafat/autoComplete.js#215]
There are use cases, where I have reference to dom element, but not the selector string. It would be great if the configuration accepted dom element as an alternative to selector string or function.

**Comment by snimavat** [comment]
I see in code, it is possible to pass dom element, however documentation is not clear abt that. it shows that selector function should return a string.

**Comment by TarekRaafat** [comment]
Hello @snimavat,

Good catch!

That's correct, as you've noticed you can use the `selector` config as a `Function` to return an `Element` instead of `String`.

Let me know if you need further clarifications.

I've just updated it in the docs.

Cheers, and have a nice day! :)
