### ISSUE TITLE
Is it possible to show all results from my json without typing ?

### ISSUE THREAD

**Issue by Senpai10** [TarekRaafat/autoComplete.js#222]
Hello,

First of all I thank you for this great library.

I wanted to know if it is possible, when you click on the search bar or a button for example, to display all the results from my JSON in the list without typing a single character.

I am sorry if I am not clear

Have a nice day !

**Comment by TarekRaafat** [comment]
Hello @Senpai10,

Thank you, I'm glad that it's useful for you.

[Answering](https://github.com/TarekRaafat/autoComplete.js/discussions/218#discussioncomment-709118) your question yes you can by using the below `config`.

Please try it and let me know if that's what you're trying to achieve or not.

```js
trigger: {
    event: ["input", "focus"],
    condition: () => true,
}
```

Cheers, and have a nice day too! :)

**Comment by Senpai10** [comment]
Thanks you su much ! It works. 
I have an another question. 

In AutoComplete options, I have: `maxResults: 5,`. As I said I want to display all my results. So I set this option to 100. But the problem is that if the user's screen is too small, the results are cut off. How to make it responsive ? Or maybe allow a scroll in the displayed results ?

Thanks again for your help and have a nice day !

**Comment by folknor** [comment]
You need to limit the size of the result popup container, by default `#autoComplete_list` and use the `overflow` CSS property. https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

**Comment by Senpai10** [comment]
Thanks you !

**Comment by Senpai10** [comment]
Hello @TarekRaafat ,

I just reopened this issue because I migrated from v8 to v10. The V10 is awesome, thanks you for your work !

But the solution provided last time doesn't work anymore. Do you have an idea how to fix this ?

`trigger: {
    event: ["input", "focus"],
    condition: () => true,
}`

Have a nice day !

**Comment by TarekRaafat** [comment]
Hello @Senpai10,

Thanks, I'm glad you like it!

Here you go, check this [code](https://tarekraafat.github.io/autoComplete.js/#/how-to-guides?id=open-list-on-focus), and let me know how it goes.

Cheers, and have a nice day too! :)

**Comment by Senpai10** [comment]
Thanks you ! Working again
