### ISSUE TITLE
Remove "files" from package.json

### ISSUE THREAD

**Issue by folknor** [TarekRaafat/autoComplete.js#225]
If you distribute src folder in the npm package, it's much easier for the editor to generate docs and autocompletion help.

Also with modern build tools like parcel 2 and vite, including autoComplete.js like `import autoComplete from "@tarekraafat/autocomplete.js/src/autoComplete"` will allow their JS tools to tree shake, optimize, and compress instead of using babel and rollup.

This is parcel 2 nightly building one of my projects with your current npm package:
```
dist/www/index.984d4fe7.js                         44.37 KB    1.06s
dist/www/index.8b01772a.js                         10.38 KB    357ms
dist/www/index.39d18735.js                        791.89 KB    5.58s
```
And this is parcel building from autoComplete.js `src` directly
```
dist/www/index.984d4fe7.js                         44.37 KB     57ms
dist/www/index.8b01772a.js                         10.38 KB     15ms
dist/www/index.cd0f409b.js                        787.88 KB    4.69s
```

This is `vite` building with current npm package:
```
dist/assets/index.bb942bdc.js                     66.71kb / brotli: 23.00kb
dist/assets/vendor.38b12ba7.js                    741.66kb / brotli: skipped (large chunk)
```
And this is `vite` building with autoComplete.js source directly:
```
dist/assets/index.7e57cf76.js                     73.48kb / brotli: 24.93kb
dist/assets/vendor.bc244387.js                    731.96kb / brotli: skipped (large chunk)
```

**Comment by TarekRaafat** [comment]
Hello @folknor,

Thanks for your suggestion, it sounds really interesting and I'll definitely check out that combo after making sure that `v10` is stable.

I've included the `src` folder in the package as per your request in `v10`.


Cheers and have a nice day! :)
