### ISSUE TITLE
I think `preInit` is broken

### ISSUE THREAD

**Issue by folknor** [TarekRaafat/autoComplete.js#229]
I was just reading the code a bit for fun and I believe `preInit` is broken. I could be mistaken. I've not tested it.

```js
export default (ctx) => {
  // Callback function to execute when mutations are observed
  const callback = (mutations, observer) => {
    mutations.forEach((mutation) => {
      // Check if "inputField" added to the DOM
      if (ctx.input) {
        // If yes disconnect the observer
        observer.disconnect();
        // Initialize autoComplete.js
        ctx.init();
      }
    });
  };
  // Create mutation observer instance
  const observer = new MutationObserver(callback);
  // Start observing the entire DOM until "inputField" is present
  // The entire document will be observed for all changes
  observer.observe(document, { childList: true, subtree: true });
};
```

`if (ctx.input)` will always fail, won't it? This is more like the code you want

```js
export default (ctx) => {
  // Callback function to execute when mutations are observed
  const callback = (mutations, observer) => {
    mutations.forEach((mutation) => {
      if (mutation.type === "childList") {
        for (let node of mutation.addedNodes) {
          if (node.nodeType === 1 && node.tagName === "INPUT") {
            // XXX Also check that it matches ctx.options.selector
            observer.disconnect()
            ctx.init()
          }
        }
      }
    });
  };
  // Create mutation observer instance
  const observer = new MutationObserver(callback);
  // Start observing the entire DOM until "inputField" is present
  // The entire document will be observed for all changes
  observer.observe(document, { childList: true, subtree: true });
};
```

I am probably misunderstanding `preInit` and `observe` completely.

**Comment by TarekRaafat** [comment]
Good catch! You're totally correct.

It looks broken the way it is currently, and your code is the correct implementation of the `observe` functionality which is meant to watch for the `input` field until it's added to the `DOM`.

Would you like to pull a PR for this one, or should I take care of it?

Cheers, and have a nice day! :)

**Comment by folknor** [comment]
You can fix it. A few more thoughts:

`mutations.forEach((mutation) => {` must be changed to `for (const mutation of mutations)` so that you can break out of the loop when you find an element that matches.

After `ctx.init()` just do `return`, probably.

And of course implement the `XXX` comment (I use XXX to mark things that _must_ be changed/fixed before release.)

**Comment by TarekRaafat** [comment]
Thanks man I'll take care of it
