### ISSUE TITLE
Item selection error

### ISSUE THREAD

**Issue by victor-paumier** [TarekRaafat/autoComplete.js#232]
Since the last version (10.0.4), it seems that there is a bug on the selection of list items.

- **To Reproduce**
1. Go to the [codepen demo](https://codepen.io/tarekraafat/pen/rQopdW) available on the documentation
2. Remove the resultsList.element option
3. Go on the search input and do a search
4. Try to select the first element of the list

- **Expected behavior**
I would expect that the clicked item would be selected, but nothing happens. Now, click on the second element, it works but the value is that of the first item instead of the one you clicked on

- **GIF**
![2021-05-31 15-10-52 2021-05-31 15_12_30](https://user-images.githubusercontent.com/13373091/120198940-f6c95b80-c222-11eb-9ede-9813d0ca3fb4.gif)

**Comment by TarekRaafat** [comment]
Hello @victor-paumier,

Good catch! thanks for reporting this.

I've fixed this issue and it will be released in the coming batch [release](https://github.com/TarekRaafat/autoComplete.js/tree/dev).


Thanks again, and have a nice day! :)

**Comment by TarekRaafat** [comment]
The mouse selection issue is resolved in [v10.1.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v10.1.0), please check it and let me know how it goes.

**Comment by victor-paumier** [comment]
It fixed! 

Thanks again for this great job, and have a nice day too :)
