### ISSUE TITLE
Keep resultsList open on "selection"

### ISSUE THREAD

**Issue by sniepoort** [TarekRaafat/autoComplete.js#236]
I can't find any mention in the docs on how to keep the resultsList open after making a selection.
I assume that the resultsList default behaviour is to close on blur, which happens when you make a selection. 
However, adding an input.focus() in the selection event doesn't trigger it to reopen.

**Comment by TarekRaafat** [comment]
Hello @sniepoort,

Try the below configuration and let me know how it goes.

```js
events: {
    input: {
        close: () => {
            autoCompleteJS.open();
        }
    }
},
```

**Comment by sniepoort** [comment]
Thanks for following up :) 
This works of course, but also means I can never close the resultList haha. I.e. it should still close on input blur, etc.
I only want it to stay open on "selection" events, i.e. on enter or click on result. But maybe I have to take care of that through traditional JS instead?
