### ISSUE TITLE
XML source

### ISSUE THREAD

**Issue by lguariento** [TarekRaafat/autoComplete.js#24]
Hello, and congratulation on the amazing job!

Is it possible to use a .xml file as a source data for autocompletion?

Luca

**Comment by TarekRaafat** [comment]
Hello @lguariento,

Many thanks I'm glad you like it! :)

Unfortunately, there is no `XML` support out of the box. But still you can covert the `XML` data source into `JSON` and plug it in.

Hope that's helpful.

**Comment by lguariento** [comment]
Thanks anyway - if, say, someone is working with a native XML database, then what you suggest is out of the question.
