### ISSUE TITLE
Is there a way to turn autocomplete back on without creating a new wrapper element around the input?

### ISSUE THREAD

**Issue by deniseismo** [TarekRaafat/autoComplete.js#245]
I can't seem to find an easy way to simply turn the autocomplete functionality back on after the autocomplete object has been uninitialized (`unInit()`). 
The `init()` core function seems like a solution, but it's also responsible for _creating wrapper element and moving the selected input inside it_, as it's stated in the docs. After a few clicks back & forth (uninit() & then init() again, for instance) we are looking at something like this:
```
<div class="autoComplete_wrapper" role="combobox" aria-owns="autoComplete_list_1" aria-haspopup="true" aria-expanded="false" wfd-id="40">
    <div class="autoComplete_wrapper" role="combobox" aria-owns="autoComplete_list_1" aria-haspopup="true" aria-expanded="false" wfd-id="55">
        <div class="autoComplete_wrapper" role="combobox" aria-owns="autoComplete_list_1" aria-haspopup="true" aria-expanded="false" wfd-id="75">
            <div class="autoComplete_wrapper" role="combobox" aria-owns="autoComplete_list_1" aria-haspopup="true" aria-expanded="false" wfd-id="99">
                <div class="autoComplete_wrapper" role="combobox" aria-owns="autoComplete_list_1" aria-haspopup="true" aria-expanded="false" wfd-id="113">
                    <div class="autoComplete_wrapper" role="combobox" aria-owns="autoComplete_list_1" aria-haspopup="true" aria-expanded="false" wfd-id="126">
                        <div class="autoComplete_wrapper" role="combobox" aria-owns="autoComplete_list_1" aria-haspopup="true" aria-expanded="false" wfd-id="139">
```
I know there's always a way to solve this by changing _my_ design, or am I missing something here as well?

**Comment by folknor** [comment]
You can set `wrapper: false` in the root of your autoComplete.js config to prevent creation of the wrapper element. That said, this should probably be fixed properly.

**Comment by deniseismo** [comment]
@folknor thank you, somehow missed this one.

**Comment by 50kudos** [comment]
`wrapper: false` just fixed the symptom of The OP's issue. The issue is not being able to fresh re-intialize autoCompletejs instance. The `unInit` function just removes all event handlers but not replace the whole process.

Ability to re-initialize a fresh instance with all previous instances (of configured input selector) removed will also give benefit of dynamic configuration. As I understand currently we can't do thing like changing `keys` dynamically based on query.
