### ISSUE TITLE
Docs for `resultsList.container`

### ISSUE THREAD

**Issue by CodeWithOz** [TarekRaafat/autoComplete.js#248]
**Is your feature request related to a problem? Please describe.**
I can't find [any documentation](https://tarekraafat.github.io/autoComplete.js/#/configuration?id=resultslist-optional) for `resultsList.container` to know how it works and how it differs from the `resultsList.noResults` option that was removed in v10. Please add some documentation.

**Thoroughly Describe the solution you'd like**
The changelog states:
> Changed: noResults API to accept boolean instead of Function to be replaced with resultsList.container

This suggests that `resultsList.container` is the replacement for `resultsList.noResults`, but there's no documentation for that and in fact `resultsList.container` has been moved to `resultsList.element`. I had custom logic that was running in the `noResults` callback, so a boolean as a replacement is not sufficient for me. How can I regain that functionality?

**Please provide a few use cases for this feature**
1. Replacing custom logic that was previously in `noResults` in v9

**Please Describe alternatives you've considered**
I don't know of any alternatives.

**Additional context**
N/A

**Comment by folknor** [comment]
You're correct that the changelog should show that `.container` was changed to `.element`.

Hopefully this helps:
```js
resultsList: {
	element: (element, data) => {
		// input = value in the input field
		// query = manipulated query
		// results = rendered results, limited by resultsList.maxResults etc
		// matches = all matches from the fetched data
		//const { input, query, matches, results } = data
		const { query, matches } = data
		if (
			matches.length === 0
		) {
			const result = document.createElement("p")
			result.innerHTML = `<span class="fa fa-exclamation-triangle"></span>No results for "${query}".`
			element.append(result)
		}
	},
	noResults: true,
}
```

**Comment by CodeWithOz** [comment]
@folknor thanks for your input. The changelog actually does show that `container` was changed to `element`, that's part of why the line I quoted is confusing. If `container` has been removed then I don't see how it can be a replacement for `noResults`.
---
Thanks for the code snippet, I'll try that and see if works.

**Comment by CodeWithOz** [comment]
@folknor thanks that works. :+1:
