### ISSUE TITLE
XHR requests are not aborted on new search start

### ISSUE THREAD

**Issue by kinguru** [TarekRaafat/autoComplete.js#255]
Is there a functionality to abort in-flight XHR requests when new request started?
For example you write in autocomplete textbox:
1. Mainb
2. Mainbo
3. Mainboard

3 XHR requests created in parallel. 
Expected result: 2 results aborted, 1 in-flight (last one)

**Comment by folknor** [comment]
No.

autoComplete.js does not perform any of the data fetching, you need to do that yourself.

```js
let xhr = new XMLHttpRequest()
new autoComplete({
	data: {
		src: async () => {
			xhr.abort()
			xhr.open(...)
			xhr.send()
			await ...
		},
		keys: ...
	},
	threshold: 3,
	debounce: 300
})
```

Or you can use a Promise and `fetch`, whatever you want.

Note the `debounce` and `threshold` properties, which assist with this somewhat, and are frankly enough in most cases.
