### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by folknor** [TarekRaafat/autoComplete.js#256]
No problem here, I am just puzzled by it:

1. start.js runs
2. await getData(ctx)
3. findMatches(queryVal, ctx)
4. if (ctx.resultsList) render(ctx)

In step 2, `ctx.feedback` is set to `data.src`, and then in step 3, `ctx.feedback` is set to `ctx.feedback = { query, matches, results }`.

In between those, I can not see that `ctx.feedback` is read anywhere?

Can this line in dataController.js
```js
ctx.feedback = data.store = typeof data.src === "function" ? await data.src(query) : data.src;
```
be changed to
```js
data.store = typeof data.src === "function" ? await data.src(query) : data.src;
```

Or what am I not seeing?

**Comment by folknor** [comment]
Also another question, because I don't know JS that well. Does this code in dataController.js change the value of `ctx.query`?

```js
  let { input, query, data } = ctx;
  query = query ? query(input.value) : input.value;
  ```
  
 Should it be
 ```js
  const { input, query, data } = ctx;

  if (data.cache && data.store) return;

  const queryVal = query ? query(input.value) : input.value;
 ```
 
 I don't code in JS that much so I'm not always sure which values are passed by reference and by value.
 
 I could have googled this before asking, but it was easier to just mention it :-)

**Comment by folknor** [comment]
There's 3 places in the code where you do `let { ... } = ctx` instead of `const { ... } = ctx`.

**Comment by folknor** [comment]
Obviously start.js would have to change `if (ctx.feedback instanceof Error) return;` to `if (ctx.data.store instanceof Error) return;` as well along with comment 1.

**Comment by TarekRaafat** [comment]
> No problem here, I am just puzzled by it:
> 
> 1. start.js runs
> 2. await getData(ctx)
> 3. findMatches(queryVal, ctx)
> 4. if (ctx.resultsList) render(ctx)
> 
> In step 2, `ctx.feedback` is set to `data.src`, and then in step 3, `ctx.feedback` is set to `ctx.feedback = { query, matches, results }`.
> 
> In between those, I can not see that `ctx.feedback` is read anywhere?
> 
> Can this line in dataController.js
> 
> ```js
> ctx.feedback = data.store = typeof data.src === "function" ? await data.src(query) : data.src;
> ```
> 
> be changed to
> 
> ```js
> data.store = typeof data.src === "function" ? await data.src(query) : data.src;
> ```
> 
> Or what am I not seeing?

The `ctx.feedback` is read through the `eventEmitter` detail.

**Comment by TarekRaafat** [comment]
> There's 3 places in the code where you do `let { ... } = ctx` instead of `const { ... } = ctx`.

Thanks for that, I've updated them all in `v10.2.4` 👍🏻

**Comment by folknor** [comment]
Ah I didn't see that :-) Thank you.
