### ISSUE TITLE
Problem with async  data

### ISSUE THREAD

**Issue by razor11** [TarekRaafat/autoComplete.js#259]
### Discussed in https://github.com/TarekRaafat/autoComplete.js/discussions/258

<div type='discussions-op-text'>

<sup>Originally posted by **razor11** July 14, 2021</sup>
I got this error when I try to fetch data from my API : TypeError: n.store.forEach is not a function
    at h (autoComplete.min.js:1)</div>

**Comment by folknor** [comment]
Sounds like your code is returning something that doesn't implement `forEach`.

From `config.data.src` you need to return an array, set, map, object, or something that can be iterated.

https://github.com/TarekRaafat/autoComplete.js/blob/master/src/controllers/dataController.js#L14
https://github.com/TarekRaafat/autoComplete.js/blob/master/src/controllers/dataController.js#L34

```js
new autoComplete({
	data: {
		src: async q => {
			let data
			await fetch(url + "?" + q, parameters)
				.then(json => (data = json))
			return data
		},
		keys: ["..."]
	},
```

**Comment by razor11** [comment]
Solved!!!! Thank you so much @folknor
