### ISSUE TITLE
Disable search engine, because correct results are coming from BE

### ISSUE THREAD

**Issue by oakleaf** [TarekRaafat/autoComplete.js#307]
Hello, I'd like to disable the search engine entirely, so all items coming from the BE is shown. But I can't find a way to go around this, since I have to specify keys. When I do this, the "autoComplete.js" search engine displays the results in another order, and not grouped together if there are more matches than in one place.

So my request is to disable the searchEngine. Maybe a suitable way to do so is to not use the keys parameter at all, together with data.src is objects?

**Comment by oakleaf** [comment]
I found out how to do this. If I dont use any keys, use the searchEngine parameter and return the whole object.

obj.searchEngine = (q, r) => r;

**Comment by adamtheapiguy** [comment]
> I found out how to do this. If I dont use any keys, use the searchEngine parameter and return the whole object.
> 
> obj.searchEngine = (q, r) => r;

can you post the whole code? I want to disable search engine and display results as is. also I need to cleanup everything to do with search engine. The api I'm calling does the search already. Is there a simplified version of the autoComplete?

**Comment by oakleaf** [comment]
Only like this;

```
    init(_data_source)
    {
        if(_data_source.src != undefined && typeof(_data_source.src) == "string")
        {
            let obj = {
                data: {
                    src: async (query) => {
                        try
                        {
                            if(this.fetch)
                            {
                                this.abort();
                                document.body.classList.add("autocomplete-searching");
                            }

                            this.fetch = abortableFetch(_data_source.src, { q: query });

                            return await this.fetch.ready();
                        } 
                        catch (error) 
                        {
                            return error;
                        }
                    }
                }
            };

            let keys = (_data_source.key != undefined && typeof(_data_source.key) == "string") ? [_data_source.key] : ((_data_source.keys != undefined) ? _data_source.keys : null);

            if(keys)
            {
                obj.data['keys'] = keys;
            }
            else
            {
                obj.searchEngine = (q, r) => r;
            }
             
            return obj;
        }
    }
```

**Comment by adamtheapiguy** [comment]
thanks for your response.

I ended up doing it like the below:

        const autoCompleteJS = new autoComplete({ // API Advanced Configuration Object
          selector: "#autoComplete",
          placeHolder: "Search our API Catalogue",
          searchEngine: function (query, record) {
            return record;
          },

it worked but I have few questions:
where is that searchEngine is defined?
How to clean up the autoComplete.js to remove everything to do with search engine. I just need a simple code to just make REST api calls and display all results coming back from the REST API call. I don't need the search engine.
