### ISSUE TITLE
Enter to select Item from Result List

### ISSUE THREAD

**Issue by KMB** [TarekRaafat/autoComplete.js#309]
I would need to be able to use the enter key to trigger the selection event, if an element is selected, but also to submit the form if no item is selected. I use the resultlist as a list of "links", where I can currently use the tab key to trigger the event. The event is a simple "window.location.href". Hitting Enter just submits the form.

Basically a configurable key to trigger ("select") an event would be great. There might be something with the resultItem events, I might be missing, though. Perhaps it is possible to intercept the Enter key here and trigger a select-event instead of a form submission?

**Comment by folknor** [comment]
https://github.com/TarekRaafat/autoComplete.js/issues/189
https://github.com/TarekRaafat/autoComplete.js/issues/224
https://tarekraafat.github.io/autoComplete.js/#/configuration?id=submit-optional

```js
events: {
	input: {
		keydown(event) {
			// Check pressed key
			switch (event.keyCode) {
				// Down/Up arrow
				case 40:
				case 38:
					event.preventDefault();
					// Move cursor based on pressed key
					event.keyCode === 40 ? autoCompleteInstance.next() : autoCompleteInstance.previous();
					break;
				// Enter
				case 13:
					if (!autoCompleteInstance.submit) event.preventDefault();
					// If cursor moved
					if (autoCompleteInstance.cursor >= 0) autoCompleteInstance.select(event);
					if (autoCompleteInstance.isOpen) {
						mysubmitfunc(autoCompleteInstance.feedback.selection)
					} else {
						mysubmitfunc()
					}
					break;
				// Tab
				case 9:
					// Select on Tab if enabled
					if (autoCompleteInstance.resultsList.tabSelect && autoCompleteInstance.cursor >= 0) autoCompleteInstance.select(event);
					break;
				// Esc
				case 27:
					// Clear "input" value
					autoCompleteInstance.input.value = "";
					autoCompleteInstance.close();
					break;
			}
		}
	}
}

```

**Comment by KMB** [comment]
First: Thank you very much! I figured out, that autoCompleteInstance is autoCompleteJS, aka the constant used in the examples to hold the configuration.

Second: I read those issues but couldn't make heads or tails out of them. But I hoped you would take a look at my issue and you didn't disappoint! Again, my gratitude.

**Comment by xenon20** [comment]
Had some problems with the code above, but this one worked for me:
`events: {
        input: {
            keydown(event) {
                switch (event.keyCode) {
                    // Down/Up arrow
                    case 40:
                    case 38:
                        event.preventDefault();
                        event.keyCode === 40 ? autocomplete.next() : autocomplete.previous();
                        break;
                    // Enter
                    case 13:
                        if (autocomplete.cursor >= 0) {
                            event.preventDefault();
                            autocomplete.select(event);
                        }
                        break;
                }
            }
        }
    }`
