### ISSUE TITLE
Separate search logic from render logic

### ISSUE THREAD

**Issue by Johann-S** [TarekRaafat/autoComplete.js#34]
Hi :)

I think, since autoComplete.js expose a class, it should be better to separate the search logics and the render logics.
It'll allow people to render the results in the way they want.

For example in my app, I would like to render the results in a `<ion-list>` element with `<ion-item>` inside, so the `<ul>` and `<li>` elements doesn't suits to me.

With that features I would be able to do that, by getting the search results and displayed them the way I want

**Comment by TarekRaafat** [comment]
Hello @Johann-S your requested enhancement has been tackled and implemented in the current new release [v5.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v5.0.0), [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js) & [CDN](https://www.jsdelivr.com/package/gh/TarekRaafat/autoComplete.js).

Check it in the [playground](https://codepen.io/tarekraafat/pen/rQopdW)

Cheers! :)

**Comment by Johann-S** [comment]
Thanks man you're awesome 👍
