### ISSUE TITLE
Wanting some help with correctly reading keys.

### ISSUE THREAD

**Issue by icsy7867** [TarekRaafat/autoComplete.js#341]
I am using the latest version. Great tool btw! However my lack of javascript might be creating an issue.  I recently made an api that returns active directory users, and I am using your tool for predictive user text.

Here is a sample returned by the API
`[{"samaccountname":"user1","mail":"empty"},{"samaccountname":"user2","mail":"First.Last@company.com"}]`

And here is my JS (mostly) successfully running:
```
<script>
        const autoCompleteJS = new autoComplete({
            selector: "#autoComplete",
            placeHolder: "Input a username or email address",
	    threshold: 3,
	    cache: true,
	data: {
	    src: async (query) => {
	      try {
	        // Fetch Data from external Source
	        const source = await fetch(`https://api.helpdesk.company.com/queries/userQuery/?attr=samaccountname,mail&user=${query}&match=partial`);
	        // Data is array of `Objects` | `Strings`
	        const data = await source.json();
		console.log(data);
	        return data;
	      } catch (error) {
	        return error;
	      }
	    },
	    // Data 'Object' key to be searched
	    keys: ["samaccountname", "mail"]
	},

            resultsList: {
                element: (list, data) => {
                    if (!data.results.length) {
                        // Create "No Results" message element
                        const message = document.createElement("div");
                        // Add class to the created element
                        message.setAttribute("class", "no_result");
                        // Add message text content
                        message.innerHTML = `<span>Found No Results for "${data.query}"</span>`;
                        // Append message element to the results list
                        list.prepend(message);
                    }
                },
                noResults: true,
            },
            resultItem: {
                highlight: true
            },
            events: {
                input: {
                    selection: (event) => {
			//console.log(event.detail.selection);
			const feedback = event.detail;
			autoCompleteJS.input.blur();
			const selection = feedback.selection.value[feedback.selection.key];
			console.log(selection);
                        autoCompleteJS.input.value = selection;
                    }
                }
            }
        });
</script>
```

User names populate/show just fine.  However I cannot get the "mail" items to automatically populate in the list even though they are in the JSON object.  I think I should be seeing the "samaccountname" and "mail" text on the right of the predicted text.

And a second question, we have ~500 users in our org.  Would it make more since to do a single query and just store that data instead of continuously querying?

Thanks!  Love your tool!

**Comment by TarekRaafat** [comment]
Hello @icsy7867,

I'm glad `autoComplete.js` came in handy for you!

> 1. Displaying custom `resultItem`

```js
resultItem: {
    element: (item, data) => {
        // Modify Results Item Style
        item.style = "display: flex; justify-content: space-between;";
        // Modify Results Item Content
        item.innerHTML = `
        <span style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">
        ${data.value.samaccountname}
        </span>
        <span style="display: flex; align-items: center;">
        ${data.value.mail}
        </span>`;
    },
    highlight: true,
},
```

> 2. Storing data instead of continuously fetching it

In your case, I would recommend you store the data instead of fetching it with every query, as you've mentioned.

You have two different approaches to doing so:
1. Rely on the `data.cache` config, which will cache the data until the next page reload.
2. Store the `data.src` data return to `localStorage` or `sessionStorage` and combine it with the `data.cache` to prevent fetching data with every query


I hope I've answered your questions; please let me know if you have any more questions or need any clarification.


Cheers! :)
