### ISSUE TITLE
General question: custom style color of search icon svg

### ISSUE THREAD

**Issue by inglesuniversal** [TarekRaafat/autoComplete.js#344]
Hello @TarekRaafat 

I can't seem to find a note on your documentation on how to change the default color of the search icon to a custom color of my choice.

Can you kindly tell me how to go about it without needing to edit your css file?

Thanks!

**Comment by TarekRaafat** [comment]
Hello @inglesuniversal,

The search icon color is not inherited from the CSS file. Instead, it's hardcoded in the icon SVG file itself.
Accordingly, you'll have to change the icon/icon color in the SVG file.

Let me know if this answers your question.

Cheers! :)

**Comment by inglesuniversal** [comment]
Yes, awesome script!
