### ISSUE TITLE
Can't update to the new version - toLowerCase()

### ISSUE THREAD

**Issue by F-Locos** [TarekRaafat/autoComplete.js#38]
Hi,

I'm looking to apply the new release to my differents projects but an error occured when searching, I mean by taping in the search bar, I get :
![image](https://user-images.githubusercontent.com/7100248/57458246-4e2db500-7271-11e9-90f9-71b5cd2aad68.png)

So, I've show the "record" var, and it's the full object of one product in the json file. It should be a string?

I really want to update this version to the v4 or the v5

**Comment by TarekRaafat** [comment]
Hello @F-Locos ,

1- Which `autoComplete.js` version are you using?
2- What is the used data src?
3- What are your configurations?

**Comment by F-Locos** [comment]
- Which version ? The last one (v4)
- The data src is an auto-generated json file which is already working with an oldest version
- And this is my configuration :
`new autoComplete({
            data: {
                src: async () => {
                    // Loading placeholder text
                    document.querySelector("#autoComplete").setAttribute("placeholder", "Chargement...");
                    // Fetch External Data Source
                    var source = await fetch(window.location.origin + '/uploads/products.json');
                    var data = await source.json();
                    // Returns Fetched data
                    return data;
                },
                key: "search"
            },
            placeHolder: transSearchBar,
            selector: "#autoComplete",
            threshold: 1,
            searchEngine: "loose",
            highlight: true,
            maxResults: 10,
            resultsList: {
                container: source => {
                    resultsListID = "autoComplete_results_list";
                    return resultsListID;
                },
                destination: document.querySelector("#insert"),
                position: "afterend"
            },
            resultItem: (data, source) => {
                var url = url_product.replace('replace', data.source.reference);
                var match = data.match.replace(" - ", ` - ${data.source.category}</b><br>`);
                return `<a href="${url}"><img src="${data.source.image}" alt="${data.source.name}" /><b>${match}</a>`;
            },
            onSelection: feedback => {
                const selection = feedback.selection;
                window.location.href = url_product.replace('replace', selection.reference);
            }
        });`

**Comment by TarekRaafat** [comment]
@F-Locos everything looks good.

Could you please try the recent release [v5.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v5.0.0), [CDN](https://www.jsdelivr.com/package/gh/TarekRaafat/autoComplete.js?path=dist%2Fjs) or [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js) and let me know if you still get the same error or not, and i'd appreciate if you could provide what browser you're using and it's version as well.

Thanks!

**Comment by F-Locos** [comment]
@TarekRaafat I tried with the v5, but still the same error on `var recordLowerCase = record.toLowerCase();`.
I'm running on the latest version of chrome (Version 74.0.3729.131 (Build officiel) (64 bits)).
I didn't change my configuration and even my file (available on https://mareld.fr/uploads/products.json).

Do you want I made a simple project to show you that ?

**Comment by TarekRaafat** [comment]
Hello @F-Locos, apologies for my super late response.

Could you please share that simple project with me?

**Comment by mauricevancooten** [comment]
I'm getting the same error message: 'TypeError: record.toLowerCase is not a function'

Using: v6.0.0

My data source is: 
`[forms: 'Sample Form'},
{brochures: 'Sample Brochure'},
{guides: 'Sample Guide'},
{videos: 'Sample Video'}]`

My autoComplete config:
`new autoComplete({
    data: {
      src: libraryDocuments,
      key: ['forms', 'brochures', 'guides', 'videos']
    },
    placeHolder: 'Find a document ...',
    selector: '#autoComplete',
    threshold: 3,
    resultsList: {
      render: true,
      container: source => {
        source.setAttribute("id", "auto-complete-results");
      },
      destination: document.querySelector('#autoComplete'),
      position: 'afterend',
      element: 'ul'
    },
    maxResults: 5,
    resultItem:{
      content: (data, source) => {
        let aLink = document.createElement('a')
        aLink.setAttribute('href', titleToFileUrl(data.match))
        aLink.innerHTML = data.match
        source.appendChild(aLink)
      },
      element: 'li'
    }
  })  `

**Comment by TarekRaafat** [comment]
Hello @F-Locos,

I was able to replicate your issue finally this time, and I've found that the problem is with the data format.

Your Data formatted as shown below:

```js
[
    {forms: 'Sample Form'},
    {brochures: 'Sample Brochure'},
    {guides: 'Sample Guide'},
    {videos: 'Sample Video'}
]
```

While the proper format is:

```js
[
    {
        forms: 'Sample Form',
        brochures: 'Sample Brochure',
        guides: 'Sample Guide',
        videos: 'Sample Video'
    }
]
```

Each record should have the exact same keys.

Please try it and let me know how it went.

Cheers! :)

**Comment by mauricevancooten** [comment]
Cool, thanks, yes that works :-)

**Comment by maciekgrzybek** [comment]
@TarekRaafat I think you've mentioned the wrong person :)

**Comment by TarekRaafat** [comment]
@maciekgrzybek my bad, sorry for that mistake :)

**Comment by maciekgrzybek** [comment]
@TarekRaafat no worries :D I was just surprised :D
