### ISSUE TITLE
If data no result

### ISSUE THREAD

**Issue by chabri** [TarekRaafat/autoComplete.js#41]
Hi, is it possible to set "if no result" on resultItem config?

EX:
if(data){
/* Do something */
}else{
/* Do something */
}

or just do:
 if (data.length){}

My problem is, if use if(data) can do something, but "else" it doesn't work, return nothing. If use data.length, return undefined... Any idea?

Thanks!

**Comment by TarekRaafat** [comment]
Hello @chabri,

Try this solution.

1- Add this method to `autoComplete.js` model file
```js
// No Results action
this.noResults = config.noResults;
```

2- Replace the `exec()` function with the below
```js
const exec = (event) => {
    // Get results list value
    const resultsList = this.resultsList;
    // Clear Results function holder
    const clearResults = autoCompleteView.clearResults(resultsList);

    // Check if input is not empty or just have space before triggering the app
    if (input.value.length > this.threshold && input.value.replace(/ /g, "").length) {
    // List matching results
    this.listMatchedResults(this.dataSrc).then(list => {
        if (list.list.length === 0) {
        this.noResults();
        } else {
        // Event emitter on input field
        input.dispatchEvent(
            new CustomEvent("type", {
            bubbles: true,
            detail: {
                event,
                query: input.value,
                matches: list.matches,
                results: list.list,
            },
            cancelable: true,
            }));
        // Gets user's selection
        // If action configured
        if (onSelection) {
            autoCompleteView.getSelection(selector, resultsList, onSelection, list);
        }
        }
    });
    } else {
    // clears all results list
    clearResults;
    }
};
```

3- Add to your `autoComplete.js` instance the below configuration
```js
noResults: () => {
  console.log("No Results");
  const result = document.createElement("li");
  result.setAttribute("class", "autoComplete_result");
  result.setAttribute("tabindex", "1");
  result.innerHTML = "No Results";
  document.querySelector("#autoComplete_results_list").appendChild(result);
},
```

4- You should be good to go! :)

I'll make sure to implement this feature properly in the coming release.

Have good day! :)

**Comment by chabri** [comment]
Wow... Fast!
 Fantastic, tested and works great! 👍 
Tanks a lot for your time

**Comment by chabri** [comment]
Hi, I'v reopen this issue, because if array value is null, then get an error, just I've solved it with:

          if(record.length){ 
            var recordLowerCase = record.toLowerCase();
          }

and

            if(record.length){
              if (recordLowerCase.includes(query)) {
                var pattern = new RegExp("".concat(query), "i");
                query = pattern.exec(record);
                return highlight ? record.replace(query, autoCompleteView.highlight(query)) : record;
              }
            }

Just for the future ;)

**Comment by TarekRaafat** [comment]
Thanks @chabri for this! :)
