### ISSUE TITLE
Works with contenteditable ?

### ISSUE THREAD

**Issue by philippejadin** [TarekRaafat/autoComplete.js#42]
I'm considering using autocompletejs instead of at.js but I'd like to know if it works with contenteditable divs instead of input forms? Thank you in advance !

**Comment by TarekRaafat** [comment]
Hello @philippejadin,

I've implemented HTML elements `ContentEditable` Input Support to the current new release [v.5.1](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v5.1.0), [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js) & [CDN](https://www.jsdelivr.com/package/npm/@tarekraafat/autocomplete.js?version=5.1.0), thanks to you!

Check it and let me know your thoughts or if you have any other issues.

Cheers! :)

**Comment by philippejadin** [comment]
That was quick ! I will try it and report back. Thanks !
