### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by frederikhors** [TarekRaafat/autoComplete.js#427]
Is this abandoned?

**Comment by TarekRaafat** [comment]
Hello @frederikhors, the `autoComplete.js` is still maintained. I might have needed to catch up with my responses recently when they required a detailed or comprehensive reply/solution. However, I still maintain the library, and I'm currently working on v11.

Please let me know how I can support you.

**Comment by frederikhors** [comment]
♥
