### ISSUE TITLE
Selection event handler does not work on IE11

### ISSUE THREAD

**Issue by g-viet** [TarekRaafat/autoComplete.js#43]
It seems `CustomEvent` & `Element.prototype.closest` are not supported on IE11.
Should we implement `CustomEvent` & `Element.prototype.closest`, or, using polyfill (corejs, etc) with babel ?

**Comment by TarekRaafat** [comment]
Hello @g-viet,

Unfortunately, IE11 support is not coming to the roadmap in the near future but it will be coming.

I would advise you to go with the polyfilling option for easier development.


Good day, Cheers! :)

**Comment by g-viet** [comment]
Hi @TarekRaafat 
Thank you for your confirming.
I'm not familiar with polyfilling, so can I make a PR for implementing `CustomEvent` & `Element.prototype.closest` first ?
We will remove later when someone can make polyfilling done with babel ?

**Comment by TarekRaafat** [comment]
Of course you can please do that would be awesome! :)

**Comment by g-viet** [comment]
Hi @TarekRaafat ,
Could you please have a look into this [PR](https://github.com/TarekRaafat/autoComplete.js/pull/44/files) ?

**Comment by TarekRaafat** [comment]
Hello @g-viet,

Thanks for your enhancement.

Have a good day! :)

**Comment by g-viet** [comment]
Cheers 🎉

**Comment by bkhushang** [comment]
IE11 issue is still there. Autocomplete search is still not populate in the IE11 browser. I have done some update in Polyfills submitted by @g-viet . And it is working fine now. 

![Edge Issue](https://user-images.githubusercontent.com/11754357/82746517-44a8b980-9dae-11ea-96a4-b728dc6af2d2.PNG)
![Edge Issue fixed](https://user-images.githubusercontent.com/11754357/82746519-483c4080-9dae-11ea-87b5-37933af0b255.PNG)

And there is also CSS issue in Microsoft EDGE. I have updated that as well.

![IE Issue](https://user-images.githubusercontent.com/11754357/82746521-4d998b00-9dae-11ea-8619-cf3b4af54a33.PNG)
![IE Issue fixed](https://user-images.githubusercontent.com/11754357/82746524-57bb8980-9dae-11ea-98ba-948fbe82029a.PNG)

**Comment by TarekRaafat** [comment]
Hello @bkhushang,

Thanks a lot for your time and effort.

Yes, sure! please do submit it you don't need to ask for permission.


Cheers, have a nice day! :)
