### ISSUE TITLE
livereload has returned

### ISSUE THREAD

**Issue by Jammmmm** [TarekRaafat/autoComplete.js#434]
Simple one.

livereload has been re-introduced into dist/autoComplete.js and is causing a slowdown in Javascript execution.

It is not present in dist/autoComplete.min.js so that's the one everyone should use until this is resolved.

**Comment by TarekRaafat** [comment]
Hello @Jammmmm,

Good catch! Thanks for reporting this issue.

I'll make sure to remove it as soon as possible.

Have a nice day! :)
