### ISSUE TITLE
Change to ES Module is incompatible

### ISSUE THREAD

**Issue by bbysaeth** [TarekRaafat/autoComplete.js#437]
In your last update you added type: "module" to your package.json but your dist files are commonjs. After this change no import is possible.

Please revert this change. Thank you.

**Comment by jules-w2** [comment]
I confirm, in the new release 10.2.8 the new `type": "module"` prevents an import from being made.

@TarekRaafat , it's possible to remove it from the  package.json ?

package.json
```json
"type": "module",
  ```

```
✘ [ERROR] No matching export in "node_modules/@tarekraafat/autocomplete.js/dist/autoComplete.min.js" for import "default"
    app/javascript/alert_autocomplete.js:1:7:
      1 │ import AutoComplete   from "@tarekraafat/autocomplete.js"
        ╵        ~~~~~~~~~~~~
```

Bests

**Comment by TarekRaafat** [comment]
Hello @bbysaeth and @jules-w2,

Thanks for bringing this issue to my attention and confirming it. The new version of `Rollup.js` required this setup to work properly `"type": "module"`.

Yet, I'll make sure to fix it as soon as possible.

Have a nice day!

**Comment by TarekRaafat** [comment]
@bbysaeth @jules-w2 Please check the last release, `v10.2.9,` and let me know if the issue persists.

**Comment by jules-w2** [comment]
it works great!
Thanks for your responsiveness @TarekRaafat  ⚡⚡⚡⚡

**Comment by TarekRaafat** [comment]
Thanks @jules-w2 for your swift support, much appreciated!
