### ISSUE TITLE
Allowing a custom search algorithm to get results

### ISSUE THREAD

**Issue by hwangm** [TarekRaafat/autoComplete.js#48]
Hi there,

I want to use a fuzzy logic search algorithm to get the results to display instead of the built in search functionality. The way I imagine this working is that in the config, the Autocomplete has a key `customSearchEngine` (or whatever makes sense) and then the value is a JS function that takes the query as an argument. The function must return an array of object results to display via Autocomplete.js's rendering functionality. 

Is this something that's possible with Autocomplete.js as is now or possibly in the future?

Thanks so much for your feedback.

**Comment by TarekRaafat** [comment]
Hello @hwangm,

I really like the idea!

It's not implemented currently, but I'll add it to the roadmap and I'll do my best to release it in the coming version.

Thanks for the good ideas have a good day!

Cheers! :)

**Comment by hwangm** [comment]
Thanks Tarek! Appreciate the quick response.

**Comment by TarekRaafat** [comment]
Try this [demo](https://github.com/TarekRaafat/autoComplete.js/blob/master/dist/js/autoComplete.min.js), I've implemented your request the "Custom Search Engine" feature.

**API config:**
```js
customEngine: (query, record) => {
  // Current record value toLowerCase
  const recordLowerCase = record.toLowerCase();
  if (recordLowerCase.includes(query)) {
    // Regular Expression Query Pattern Ignores caseSensetive
    const pattern = new RegExp(`${query}`, "i");
    // Search for a match Query in Record
    query = pattern.exec(record);
    // Returns the match
    return record;
  }
}
```
- `query`: returns user's search query 
- `record`: returns each record from the data source

<br>

**How it works:**

The `customEngine` function should contain your custom search algorithm and returns each match individually as a `String` not in an `Array` form.
`autoComplete.js` runs the function automatically over each record so you don't have to do it manually or return an `Array` already.

Let me know your thoughts on it.

**Comment by hwangm** [comment]
Hi Tarek,

I think I failed to include a key part of the spec that I was looking for. I was envisioning that my custom engine would contain the dataset that is being searched rather than coming from the Autocomplete instance. 

Essentially, what I am hoping is that there's a way to totally separate the searching logic. The process would be something like this:
- user enters some input into an Autocomplete instance input
- when the criteria are met to trigger a search, the Autocomplete sends the query to some function that returns an Array of results
- the Autocomplete instance takes the results and populates the dropdown
- the developer can configure the same handlers for interacting with the dropdown as usual

If I'm interpreting the customEngine parameter correctly, it still relies on the dataset from the Autocomplete instance. Let me know if this is something that would still make sense in your roadmap, if not I understand!

**Comment by TarekRaafat** [comment]
Hello @hwangm,

Please correct me if got you wrong.

You need to be able to set new data source separate from the one you specify inside `autoComplete.js` instance that would have a different search logic aside form the one inside `autoComplete.js` as well.

If that's correct could you please tell me what's gonna be the purpose or the use case of having such a capability?

**Comment by hwangm** [comment]
Hi Tarek, that's correct. The use case for me is that I like the customizable dropdown and selection functionality of autocomplete.js, but had more complex search needs (fuzzy searching) that is currently beyond what autocomplete.js can provide at the moment. 

In the end what I did is create a simple dropdown of my own and that seems to be sufficient for my needs.

**Comment by TarekRaafat** [comment]
I believe that now after adding the new `customEngine` to the library what you're seeking is achievable by `autoComplete.js` you just set your dataset within your `autoComplete.js` instance and use your own custom fuzzy search algorithm through `customEngine`.

If you tried it and it didn't satisfy your needs please let me know exactly how we can implemented what you're looking for into the library.
