### ISSUE TITLE
Token not defined error

### ISSUE THREAD

**Issue by apasric4** [TarekRaafat/autoComplete.js#49]
Hi

Here is a link to my fiddle:
https://jsfiddle.net/apasric4/x6w4trv9/1/

This was actually working for a few moments, but then later it stopped showing the drop-down menu after I would type something in. You're supposed to be able to type something and the default drop-down menu of food and drinks is supposed to show up, but now it is not. So I know something is wrong. 

In my console, I keep getting a token is not defined error. 

What could be the issue?

**Comment by TarekRaafat** [comment]
Hello @apasric4,

First of all, I'll assume you're using a proper data source instead of the one in JSFiddle because this one is dummy and not working.

Secondly,  I guess the results list could be hidden, so try adding the below to your css file and let me know how it went.

```css
#autoComplete_results_list {
   display: block;
   bottom: -120px;
   right: 433px;
}
```

**Comment by kanine** [comment]
When trying your sample code using an API I've made a small modification, but the 'query' is not being passed into the function call...

` const source = await fetch(`https://site.test/api?q=${query}`);`

> Uncaught (in promise) ReferenceError: query is not defined

That's a working endpoint, but as soon as it no longer throws the following error once the query variable is removed.

**Comment by TarekRaafat** [comment]
Hello @kanine,

The `${query}` in the sample code was referring to below defined variable that reads from input field the users typed value.

```js
// User search query
const query = document.querySelector("#autoComplete").value;
```

So the entire data method block looks like this

```js
  data: {
    src: async () => {
      // Loading placeholder text
      document.querySelector("#autoComplete").setAttribute("placeholder", "Loading...");
      // API key token
      const token = "this is the API token number";
      // User search query
      const query = document.querySelector("#autoComplete").value;
      // Fetch External Data Source
      const source = await fetch(`https://www.site.test/api/search?key=${token}&q=${query}`);
      const data = await source.json();
      // Post loading placeholder text
      document.querySelector("#autoComplete").setAttribute("placeholder", "Food & Drinks");
      // Return Fetched data
      return data.recipes;
    },
```

Please try it and let me know how it went.

Cheers! :)

**Comment by kanine** [comment]
Thanks, that's what I had ended up doing anyway so all good. I just thought there may have been another object reference I should have been using.
