### ISSUE TITLE
Is there a way to compose autocomplete suggestions?

### ISSUE THREAD

**Issue by mimescua** [TarekRaafat/autoComplete.js#50]
I just, was trying to compose the autocomplete suggestions in a way like:
![image](https://user-images.githubusercontent.com/4094190/60827197-46a56200-a175-11e9-9936-adac2a144e6d.png)

* I'm just autocompleting the CITY name, state and country are part of the same object.

How can i do that?

**Comment by TarekRaafat** [comment]
Hello @mimescua,

Assuming that your data source is an arrray of objects, each object has key for (City, State, Country).

Through `resultItem` / `content` API, use`data` parameter with the `value` key and select the desired key that's needed to be displayed in the `autoComplete.js` result item as shown below.

```js
resultItem: {
	content: (data, source) => {
                source.innerHTML = `${data.value.city}, ${data.value.state},${data.value.country}`;
	},
	element: "li"
}
```

Find [CODEPEN](https://codepen.io/tarekraafat/pen/wLQdjj) project for this example.

Please try it and let me know how it went.

Cheers! :)

**Comment by mimescua** [comment]
Working fine, thanks!!!.

` source.innerHTML = `${data.match}, ${data.value.state}, ${data.value.country}`;`
