### ISSUE TITLE
Select first item on enter

### ISSUE THREAD

**Issue by zippy84** [TarekRaafat/autoComplete.js#52]
Hello.

How can I set the first item in the result-list, when the user press enter, without selecting it?

```Javascript
inp.addEventListener('autoComplete', (e) => {
    let detail = e.detail;

    if (detail.event.key == 'Enter'
        && detail.matches == 1) {
        // ???
        // onSelection should be triggered with the first item
    }

});
```

**Comment by TarekRaafat** [comment]
Hello @zippy84,

I hope the below snippet achieves what you're after

```js
document.querySelector("#autoComplete").addEventListener("autoComplete", function(event) {
  const key = event.detail.event.which || event.detail.event.keyCode;
  if (key === 13) {
    console.log(event.detail.results[0]);
  }
});
```

Please try it and let me know how it went.

Have a good day, cheers! :)

**Comment by zippy84** [comment]
No, the event-handler is not my problem. I want to simulate the click on the first item in the result list. The onSelect-function should be fired. Something like $(...).children().first.trigger('mousedown') doen't work.

**Comment by zippy84** [comment]
I found the problem. This is my code:

```Javascript
inp.addEventListener('autoComplete', (e) => {
    let detail = e.originalEvent.detail;
    if (detail.event.key == 'Enter'
        && detail.matches > 0) {
        let f = this.a.resultsList.view.children.item(0);
        let ev = new Event('mousedown');
        f.dispatchEvent(ev);
    }
});
```

The mousedown doesn't work, because there is no event-listener on any item in the result-list. The autoComplete-event is fired on line https://github.com/TarekRaafat/autoComplete.js/blob/e27a6b83fc2f8285b52b35c906ec723cb13a5ef8/dist/js/autoComplete.js#L336

A few lines later getSelection will be called...

I think `eventEmitter(event, list);`should be followed after the `if {...} else {...}`-block.

**Comment by zippy84** [comment]
Here is a solution:

```Javascript
inp.addEventListener('autoComplete', (e) => {
    let detail = e.originalEvent.detail;
    if (detail.event.key == 'Enter'
        && detail.matches > 0) {
        this.a.listMatchedResults(this.a.dataSrc).then(() => {
            let f = this.a.resultsList.view.children.item(0);
            let ev = new Event('mousedown');
            f.dispatchEvent(ev);
        });
    }
});
```

`this.a` is the autoComplete-instance.

**Comment by TarekRaafat** [comment]
I'm glad you came up with a suitable solution and thanks for sharing it.

I really like your approach, and I have another approach as well in case you want to capture the original event type.

```js
document.querySelector("#autoComplete").addEventListener("autoComplete", (event) => {
  const detail = event.detail;
  if (detail.event.key === "Enter" && detail.matches > 0) {
    detail.selection = detail.results[0];
    autoCompletejs.onSelection(detail);
    autoCompletejs.resultsList.view.innerHTML = "";
  }
});
```

**Comment by maximilian** [comment]
2020 solution:
```
document.querySelector("#autoComplete").addEventListener("keydown", event => {
	if(event.key === 'Enter') {
		    ac.listMatchedResults(ac.dataStream).then(() => {
            let f = ac.resultsList.view.children.item(0);
            let ev = new Event('mousedown');
            f.dispatchEvent(ev);
        });
	}
});
```

**Comment by TarekRaafat** [comment]
Hello @maximilian,

That's great!
Is it tested?


Cheers! :)

**Comment by relaxeaza** [comment]
Newer versions doesn't trigger the event `autoComplete` when pressing Enter.

**Comment by zippy84** [comment]
I want to migrate my script towards the new version. This does not work, because there is no `listMatchedResults`, `dataStream` and `view` anymore:

```js
ac.listMatchedResults(ac.dataStream).then(l => {
    const f = ac.resultsList.view.children.item(0),
        ev = new Event('mousedown');
    f.dispatchEvent(ev);
});
```
How can I achieve the same with the new version?

**Comment by TarekRaafat** [comment]
Hello @zippy84,

You can use the `rendered` event instead as per the [demo](https://github.com/TarekRaafat/autoComplete.js/blob/master/dist/js/index.js#L21-L24) file which fires after fetching data and rendering the `resultsList`.

Try it let me know how it goes.

Cheers! :)
