### ISSUE TITLE
What's autoComplete.js greatest weaknesses?

### ISSUE THREAD

**Issue by TarekRaafat** [TarekRaafat/autoComplete.js#53]
Hello `autoComplete.js` users,

Hope you're all doing well and enjoying using `autoComplete.js`.

I'm always trying to do my best to improve and maintain `autoComplete.js` as much as possible.

That's why I've thought about performing a monthly health checkpoint status, to see how `autoComplete.js` is doing with you and what should be done in-terms of improvement next.

So, every month I'm going to open a new issue for **10 days** with the above title, for you to contribute in with your valuable feedback on the library mentioning `What's autoComplete.js greatest weaknesses?` out of your personal experience using it.

Based on your feedback, the most mentioned/voted weakness, it will take the first place on the [Roadmap](https://tarekraafat.github.io/autoComplete.js/#/?id=_6-roadmap) under the proper section with the highest priority, while the rest comes after to be placed next month.

Thank you so much for your support and contributions to make `autoComplete.js` better!

<br>

Happy Development, Cheers! :)

**Comment by cliffordfajardo** [comment]
Hey @TarekRaafat - left a suggestion here #54.

**Comment by ve3** [comment]
I'm not clear about data format too. From this page ( https://tarekraafat.github.io/autoComplete.js/demo/db/generic.json ) I think data format is
```
[
    {"key1": "value1", "key1.2": "value1.2"},
    {"key2": "value2", "key2.2": "value2.2"},
]
```
and something different (more complex) like this is not possible?
```
{
    "province": [
        {"id": "1", "name": "aaa"},
        {"id": "2", "name": "aAaAa"}
    ],
    "district": [
        {"id": "123", "province_id": "1", "name": "xxx"},
        {"id": "124", "province_id": "1", "name": "xxxA"}
    ],
}
```
