### ISSUE TITLE
Suggestion: Use typescript

### ISSUE THREAD

**Issue by cliffordfajardo** [TarekRaafat/autoComplete.js#54]
I love this project & have been experimenting with it for the past few days!

I think, something that would benefit this project now & in the long term is if it used Typescript.

As the feature set of this library increases
![Screen Shot 2019-07-24 at 9 51 09 PM](https://user-images.githubusercontent.com/6743796/61846773-4091cf80-ae5d-11e9-90fd-23270071be46.png)

the probability of bugs will too. We can reduce that number with help of TS.

**Setting up configs & builds is a pain**, but if we use [TSDX - Zero-config CLI for TypeScript package development](https://github.com/palmerhq/tsdx) it literally would take only a few minutes to setup a typescript environment.

**Then**, it's just a matter of moving autocomplete.js's `src` files into the `src` directory that TSDX generates. 
![Screen Shot 2019-07-24 at 9 56 36 PM](https://user-images.githubusercontent.com/6743796/61847079-273d5300-ae5e-11e9-977c-e212b672bb7f.png)

I've used TSDX in dozens of my projects and it's really smooth experience!

I wanted to submit a PR of just converting all the files to end with `.ts` but realized it would be wise to check in with you on the direction of your project.

**Key features of [TSDX](https://github.com/palmerhq/tsdx#readme)** (has lots of gifs go check it out 😄 )
- uses rollup under the hood like this project
- has lots of sane defaults for building optimized libraries. 
	- Check out this feature of TSDX which outputs [a package size snapshot](https://github.com/jaredpalmer/formik/blob/master/.size-snapshot.json).
	- sets up a [jest](https://jestjs.io/) testing environment automatically.

**Other benefits of adopting typescript:**
- Optional static typing (the key here is optional)
- people using the autocomplete.js library as users will have access to intellisense/autocompletions while their using it in their own projects thanks to typescripts `@types`
- better editor support (VScode, modern editors etc)
- autocompletion of the codebase's API
- easier refactoring thanks to modern editor tooling _(probably 1 of my favorite features of typescript & typed languages)_

Thoughts, concerns?

**Comment by TarekRaafat** [comment]
Hello @cliffordfajard,

Sorry for my late feedback.

Thank you so much, I'm glad you love autoComplete.js! =D

I get your points on the benefits of migrating the entire project from JS to TS that it might help the library from maintainability and easy development perspectives but unfortunately, I have currently nearly zero knowledge about TS I need to research and learn more about it and about the benefits of such a move first, to evaluate if it's worth it or not at least for the short term, especially that one of the core concepts of the library that it's `Pure Vanilla JS` so this is going to be a core drastic change.

I've started already reading and researching about it now, and I'll let you know as soon as I reach a decision on it.


Thank you so much again for your passion and effort, have a good day! :)

**Comment by iacobfred** [comment]
Here's an alternative library for anyone who wants TypeScript:

https://github.com/kraaden/autocomplete

(I'm not affiliated.)
