### ISSUE TITLE
Selection does not work on mobile devices

### ISSUE THREAD

**Issue by Mavellol** [TarekRaafat/autoComplete.js#64]
Most likely you need to implement touchstart event support

**Comment by TarekRaafat** [comment]
Hello @Mavellol,

Could you please provide some details.

1. Mobile OS type (iOS, Android, etc...)
2. Browser type and version
3. autoComplete.js configurations
4. Behavior in a desktop browser (Working or Not Working too)

Good day, cheers! :)

**Comment by Mavellol** [comment]
I'm sorry, it seems this is my mistake
