### ISSUE TITLE
How to use autocomplete in my own project, not in your cloned repo.

### ISSUE THREAD

**Issue by GiorgioMartini** [TarekRaafat/autoComplete.js#66]
**Is your feature request related to a problem? Please describe.**

**Thoroughly Describe the solution you'd like**
How do i use autocomplete in my own project, you describe how to use it in your cloned repo, which has all the necesary images and html markup needed however, if i want to use it in my own project, which is 99.99% of the people, there is no explanation on how to use it.

**Please provide a few use cases for this feature**
1. ...
2. ...

**Please Describe alternatives you've considered**

**Additional context**

**Comment by TarekRaafat** [comment]
Hello @GiorgioMartini,

Kindly find below all the resources and instructions you would need to use `autoComplete.js`

1. [Installation](https://tarekraafat.github.io/autoComplete.js/#/?id=installation)

2. [How to use?](https://tarekraafat.github.io/autoComplete.js/#/?id=how-to-use)

3. [Live example](https://codepen.io/tarekraafat/pen/rQopdW?editors=0010)

4. [API Configurations](https://tarekraafat.github.io/autoComplete.js/#/?id=api-configuration)


Please, let me know if you faced any challenges or need any kind of help.

Have a good day, cheers! :)
