### ISSUE TITLE
Applying pre-processing to certain fields before search is executed

### ISSUE THREAD

**Issue by carlosb1504** [TarekRaafat/autoComplete.js#68]
Hi all, thanks for this great little library. It has come in really useful in our latest project. 

How about the idea of implementing a set of 'fieldProcessors' which are able to pre-process the content of particular fields before such time as the actual search is done?

As an example, in our particular use case, the data source coming via ajax was a list of people, including a Name & Date of birth field, both of which to be used as keys. We wanted the user to be able to type in either a name or a date of birth and for the matches to come back accordingly. See an example of the data here:

```
[{
"Name": "Bob Monkhouse",
"Area": "Live Case",
"DOB": "1932-02-19T00:00:00",
"URL": "/Individuals/Details/25"
},
{
"Name": "Barry Chuckle",
"Area": "Live Case",
"DOB": "1956-09-13T00:00:00",
"URL": "/Individuals/Details/27"
},
{
"Name": "Jon Snow",
"Area": "Live Case",
"DOB": "1988-08-22T00:00:00",
"URL": "/Individuals/Details/28"
}]
```

As you can see the DOB is a DateTime field as converted by the standard ASP.NET JsonConvert methods, it is not exactly how a user would want to search for that date, that is to say it's not a 
particularly 'human readable' format, especially here in the UK where the standard date format is DD/MM/YYYY.

I could have changed my method in the solution returning this data to format the date in a human readable way, but I don't think that's the way to go as this data may eventually be consumed by other systems down the line which may require a more standard format.

The solution, I added a new object to the constructor of Autocomplete.js, which is a 'fieldProcessors' object. This object is keyed as per the keys of the data, with the value being a function or reference to a function which will process the content of that field in some way and return the result. Please see below a portion of updated instantiation of my autocomplete object:

```
    const autoCompletejs = new autoComplete({
        data: {
            src: async () => {
                // Loading placeholder text
                document
                    .querySelector("#autoComplete")
                    .setAttribute("placeholder", "Loading...");
                // Fetch External Data Source
                const source = await fetch(
                    "@Url.Action("AllPermittedIndividualsByArea", "CLIndividuals")"
                );
                const data = await source.json();
                // Post loading placeholder text
                document
                    .querySelector("#autoComplete")
                    .setAttribute("placeholder", "Who are you looking for? Try typing a name or date of birth");
                // Returns Fetched data
                return data;
            },
            key: ["Name", "DOB"],
            cache: false
        },
        customEngine: customSearch,
        fieldProcessors: {
            "DOB": function (fieldVal) {
                return moment(fieldVal).format("DD/MM/YYYY");
            }
        },
        threshold: 2,
        debounce: 300,
        selector: "#autoComplete",
```

Note that my field processor for the DOB field in this case, uses the moment.js library to convert my date field to the desired format, but I could have done anything here.

Here are my amendments to the autocomplete.js file itself:

pulling in the config to the internal object:
```
  var autoComplete =
  function () {
    function autoComplete(config) {
      _classCallCheck(this, autoComplete);
      this.selector = config.selector || "#autoComplete";
      this.data = {
        src: function src() {
          return typeof config.data.src === "function" ? config.data.src() : config.data.src;
        },
        key: config.data.key,
        cache: typeof config.data.cache === "undefined" ? true : config.data.cache
      };
      // Get the collection of fieldProcessors from the config passed in (if relelvant)
      this.fieldProcessors = config.fieldProcessors ? config.fieldProcessors : false;
      this.query = config.query;
      this.triggerEvent = config.triggerEvent || ["input"],
      this.searchEngine = config.searchEngine === "loose" ? "loose" : "strict";
      this.customEngine = config.customEngine ? config.customEngine : false;
      this.threshold = config.threshold || 0;
```

Applying the function to the relevant field before doing the comparison against the user's query:
```
            var search = function search(key) {
              var recordValue = key ? record[key] : record;
              recordValue = _this.fieldProcessors ? (_this.fieldProcessors[key] ? _this.fieldProcessors[key](recordValue) : recordValue) : recordValue;                  
              if (recordValue) {
                  var match = _this.customEngine ? _this.customEngine(_this.queryValue, recordValue) : _this.search(_this.queryValue, recordValue);
                if (match && key) {
                  resList.push({
                    key: key,
                    index: index,
                    match: match,
                    value: record
                  });
                } else if (match && !key) {
                  resList.push({
                    index: index,
                    match: match,
                    value: record
                  });
                }
              }
            };
```

Hopefully this is useful to someone. There may well be better ways to achieve what I was trying to do but this worked for me and was a nice learning experience in adapting a library for my particular needs.

Happy to hear your thoughts.

Cheers

**Comment by TarekRaafat** [comment]
Hello @carlosb1504,

I'm really glad you like `autoComplete.js` and that it came in handy for you! :)

I like your enhancement proposal and I highly appreciate the time and effort you've put into it but have you tried the `resultItem.content` API for the same result as shown in the code example below?

```js
const autoCompletejs = new autoComplete({

  resultItem: {
    content: function (data, source) {
      if (data.key === "DOB") {
        source.innerHTML = moment(fieldVal).format("DD/MM/YYYY");
      } else {
        source.innerHTML = data.match;
      };
    }
  }

})
```

Please try it and let me know if it achieved the result you're after or not.


Have a good day, cheers! :)

**Comment by carlosb1504** [comment]
Hi @TarekRaafat - Thanks for your reply.

If I'm understanding correctly, the `resultItem.content` wouldn't help in my particular scenario.

I do use this in order to apply formatting in order present the results of the search to the user. However, in my scenario I need to process some attributes of the source data **before** the search is performed in order to get that data into the format that the user wants to search for it. 

So given this one piece of data:

```
{
"Name": "Jon Snow",
"Area": "Live Case",
"DOB": "1988-08-22T00:00:00",
"URL": "/Individuals/Details/28"
}
```

If the data is left unprocessed, and I want the user to be able to search using the 'DOB' field as a key. Then they would have to search for '1988-08-22' in order to get a match. What I want is for the user to be able to search in their local 'human readable' date format which in the UK would be '22/08/1988' and still get the result hit and match Jon Snow.  (obviously that format might change depending on the location of the user, another reason not to change the data at source and to do the formatting at the client side) 

Does that make sense? For that reason I brought in the 'fieldProcessors' object which applies the given function to the data in each field, transforming it as desired **prior to the search being performed**.

**Comment by TarekRaafat** [comment]
Alright, if I got it right this time then I believe that `query.manipulate` API should be achieving the same result as shown below, am I right? 

```js
const autoCompletejs = new autoComplete({
  query: {
    manipulate: function (fieldVal) {
      return moment(fieldVal).format("DD/MM/YYYY");
    },
  },
});
```

**Comment by carlosb1504** [comment]
Ah, I see, so that gives you the ability to transform the user's query to fit the format of the source data. That hadn't occurred to me. I guess it's the opposite of what I was proposing which was to transform the source data to the format I'm expecting my users to enter.

It could be made to work as you say, but I think you would lose the partial matching in that scenario. So for example with Jon Snow again as above. Using my proposal a user could enter as the query '22/0' and the library would match that as a sub string of '22/08/1988' which is how the field looks after the `fieldProcessor` has done its work. However using the manipulate method, the user would have to type a full date in, before it could be converted to a date which matches the source data, and a match eventually found.

**Comment by TarekRaafat** [comment]
Now I got what you mean.

Try the `data.src` API as shown in the below example and let me know how it went.

```js
const autoCompletejs = new autoComplete({
    data: {
        src: async () => {
            // Loading placeholder text
            document
                .querySelector("#autoComplete")
                .setAttribute("placeholder", "Loading...");
            // Fetch External Data Source
            const source = await fetch(
                "@Url.Action("AllPermittedIndividualsByArea", "CLIndividuals")"
            );
            let data = await source.json();
            // Pre-prossesor
            data.forEach(record => {
                record.DOB = moment(record.DOB).format("DD/MM/YYYY");
            });
            // Post loading placeholder text
            document
                .querySelector("#autoComplete")
                .setAttribute("placeholder", "Who are you looking for? Try typing a name or date of birth");
            // Returns Fetched data
            return data;
        },
        key: ["Name", "DOB"],
        cache: false
    },
})
```

**Comment by carlosb1504** [comment]
Hi. Thanks for the replies. I can see how that would work. Maybe I was over engineering things 😊

Cheers

**Comment by TarekRaafat** [comment]
No worries man, we all do sometimes! :sweat_smile:

I'm glad that we've found a way to achieve the results you're after.

And thank you for the new use case you've provided to the community!

Have a good day, cheers! :blush:
