### ISSUE TITLE
Add keyboard driven final selection

### ISSUE THREAD

**Issue by jfkw** [TarekRaafat/autoComplete.js#7]
When filtering autocomplete options, often one gets down to a small number of matches, after which point further filter string typing becomes undersirable. Using the provided demo data set, an example of more usable input would be to type "red snapper" (down-arrow) (finalize selection key TBD) to select "Red Snapper - Fillet, Skin On".

**Comment by TarekRaafat** [comment]
@jfkw totally agree with you, **"Keyboard Navigation/Selection"** is essential that's why it took place on the [Roadmap](https://tarekraafat.github.io/autoComplete.js/#/?id=_6-roadmap) under the "Functionality" section. Will make sure to prioritize it, thanks!

**Comment by TarekRaafat** [comment]
@jfkw check [v2.1.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v2.1.0) just released and it has Support for keyboard `Arrow` and `Tab` navigation, here is the [demo](https://tarekraafat.github.io/autoComplete.js/demo/).

let me know your feedback.

**Comment by rdetert** [comment]
The arrows work great, however, if I hit "Enter" to select the option, the form submits. Is there a way around this?
