### ISSUE TITLE
how to suggest children data when input parent data

### ISSUE THREAD

**Issue by hagiwara-lvgs** [TarekRaafat/autoComplete.js#70]
location table constracture
  -id
  -name
  -parent_id

data in location table
{'id' => 1, 'name' => 'food', 'parent_id' => 1},
{'id' => 2, 'name' => 'carry', 'parent_id' => 1}

when input  **food** in input field, display **food carry**  in suggest list.

How can I achieve this?

**Comment by TarekRaafat** [comment]
Hello @hagiwara-lvgs,

Sorry for my late reply.

I'm currently looking into it and will let you know as soon as I find out a good solution for your case.

Providing a bigger sample of your `data.src` and more information on your use-case would be so much helpful tho.

Cheers, have a nice day! :)
