### ISSUE TITLE
CSS selector uses element id

### ISSUE THREAD

**Issue by xtellurian** [TarekRaafat/autoComplete.js#73]
The CSS uses a selector based on the id "autoComplete". It makes it difficult to have multiple auto-completes on the same page (as they have the same id) and have them both styles in the default way.

https://github.com/TarekRaafat/autoComplete.js/blob/master/dist/css/autoComplete.css#L6

I think it might be helpful to be able to apply the CSS via classes, rather than the id.

**Please Describe alternatives you've considered**
I'm considering downloading the CSS and hosting my own copy.

**Comment by xtellurian** [comment]
One workaround:

Add an extra class to your input like this:

```css
<input id="autoComplete" class="autoCompleteWorkaround" >
```

Then you can use the class in the selector, eg:

```js
resultsList: {                       
            ...
            destination: document.querySelector(".autoCompleteWorkaround"),
          ...
        },
```

**Comment by TarekRaafat** [comment]
Hello @xtellurian,

Thanks for sharing your case and your workaround for it.

The `id` is mainly being used by `autoComplete.js` for a specific purpose which is to point at "select" the input field that has to be unique in case of multiple fields are being used at the same page.
This is considered as a good practice for selecting a unique HTML element that's not repeated, while still `class` selection is supported by `autoComplete.js` as well but not recommended.

Adding the input field style to the library's main stylesheet through the `id` was done just to get developers started as quickly as possible, and it could be overwritten easily by adding a `class` or a new `id` to the input field with the required styling from a separate CSS sheet, as shown in the below example.

> N.B.: `resultsList` render destination is being handled automatically by `autoComplete.js` pointing at the specified `selector` no need to be handled manually.

- First Instance

```html
<input id="autoComplete-01" class="autoComplete-01" type="text">
```
```js
 // The autoComplete.js Engine instance One
const autoComplete_01 = new autoComplete({
  selector: "#autoComplete-01",

});
```

- Second Instance

```html
<input id="autoComplete-02" class="autoComplete-02" type="text">
```
```js
 // The autoComplete.js Engine instance Two
const autoComplete_02 = new autoComplete({
  selector: "#autoComplete-02",

});
```


Cheers and have a nice day! :)

**Comment by xtellurian** [comment]
Hey @TarekRaafat  thanks for the reply :)

Considering the situation with multiple autoComplete engines, like so:

```html
<input id="autoComplete-02" class="autoComplete-02" type="text">
```

```js
// The autoComplete.js Engine instance One
const autoComplete_01 = new autoComplete({
  selector: "#autoComplete-01",
});
```

Won't the CSS fail to target correctly the <input> element, because the CSS is targetting an element with `id="autoComplete" ?

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
