### ISSUE TITLE
Promise checking bug in 7.0.1

### ISSUE THREAD

**Issue by braco** [TarekRaafat/autoComplete.js#75]
https://github.com/TarekRaafat/autoComplete.js/blob/master/src/models/autoComplete.js#L337-L346

The promise here is resolving to an actual value, lets say Array, then erroring because that code is trying to run [].then(...)

I'm not quite clear on what the intention was with some of that, like `this.dataStream = this.dataStream;`, but I think you can solve what you were trying to do with:

```
        Promise.resolve(this.dataStream)
        .then(response => {
          this.dataStream = response;
          exec(event);
        })
```

The .resolve() will wrap whatever value in a promise, including another promise, so you can safely execute .then without checking for type.

eg, these should both work:

`Promise.resolve([])`
`Promise.resolve(Promise.resolve())`

**Comment by TarekRaafat** [comment]
Hello @braco,

Thank you! I didn't notice that.

I've fixed it check it [here](https://github.com/TarekRaafat/autoComplete.js/tree/master/dist/js) and let me know.

Cheers! :)

**Comment by braco** [comment]
@TarekRaafat looks good, are you going to publish to npm?

**Comment by TarekRaafat** [comment]
Hello @braco,

I've just published it [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js), kindly check it and let me know if there's anything behaving unexpectedly.

Cheers! :)
