### ISSUE TITLE
Duplicate values for a key always returns the first row in JSON set

### ISSUE THREAD

**Issue by plungerman** [TarekRaafat/autoComplete.js#78]
All systems
All browsers
All OS

when you have two values that are identical in your JSON data, the first one is always selected, even if you click on match that appears after the first one. for example, in the Demo site:

https://tarekraafat.github.io/autoComplete.js/demo/

you have two "food" items that have a value of "Sauce - Caesar Dressing". the cities value for those two items are "Palestina de los Altos" and "Kelasuri":

    {
        "food": "Sauce - Caesar Dressing",
        "cities": "Palestina de los Altos",
        "animals": "Monkey, vervet"
    },
    {
        "food": "Sauce - Caesar Dressing",
        "cities": "Kelasuri",
        "animals": "Alligator, american"
    },

when you start typing "Sauce" and you select the second listing for "Sauce - Caesar Dressing", the selection value should be the one where "cities" is equal to "Kelasuri". but that is not the case. the selection value is always "Palestina de los Altos".

we use this most excellent autoComplete.js library for selecting students for various forms. when you start typing "Smith", for example, 30 or so items/students are displayed. no matter which student you click on, it always selects the first one in the result set.

**Comment by TarekRaafat** [comment]
Hello @plungerman,

That's a really good catch!

Thank you so much for reporting this bug I've never noticed it before.
I've checked it and the behavior was exactly as you've mentioned above.

I added this issue to my list already and gave it the highest priority, will start working on it this weekend in-order to release the fix asap and I'll keep you posted.


Thanks again and have a nice day! :)

**Comment by plungerman** [comment]
excellent. thank you, tarek

**Comment by TarekRaafat** [comment]
I've looked into it already and found the root cause of the issue to be the method of result selection that's based on the result's `data-attribute` value which is carrying the name of the result.

That's why in your case "having multiple identical named results" keeps getting you the same first result regardless of your selection because the loop returns every time the first match it finds.

The next step to fixing this issue is figuring out a way to distinguish identical results.

Will let you know as soon as I figure out a neat and solid solution.

**Comment by TarekRaafat** [comment]
The bug has been fixed already in the current version `7.0.3`, kindly check it and let me know your feedback on it.

Cheers! :)

**Comment by plungerman** [comment]
i have installed the 7.0.3 release and everything seems to be working perfectly. thank you for your assistance, @tarekraafat!
