### ISSUE TITLE
Compatibility Javascript IE11

### ISSUE THREAD

**Issue by F-Locos** [TarekRaafat/autoComplete.js#79]
Hi,

Your setup script in the index.js is not transpiled in the es5 format. 
It makes our websites unusable on IE just because of this little thing. It brokes every script anyway.

If some one as a fix for that, it would be great to post it there.
I'm not an expert using gulp/babel to solve this problem.

Thank you :)

**Comment by EmilStenstrom** [comment]
To convert the example script to ES6 you can use Babel's online tool: https://babeljs.io/en/repl

**Comment by F-Locos** [comment]
> To convert the example script from ES6 to ES5 you can use Babel's online tool: https://babeljs.io/en/repl

I tried, unsuccessfully. I'm not good at all in js/babel. Close it so, thanks
