### ISSUE TITLE
Runtime error with rollup

### ISSUE THREAD

**Issue by mikob** [TarekRaafat/autoComplete.js#8]
Trying to compile with [rollup](https://github.com/rollup/rollup) 
```
import * as autoComplete from '@tarekraafat/autocomplete.js/dist/js/autoComplete';
```

I get a warning: 
```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en#error-this-is-undefined
node_modules/@tarekraafat/autocomplete.js/dist/js/autoComplete.js
3:   typeof define === 'function' && define.amd ? define(factory) :
4:   (global.autoComplete = factory());
5: }(this, (function () { 'use strict';
     ^
6:
7:   function _classCallCheck(instance, Constructor) {
```

and then a runtime error from the global.autocomplete... 
`Cannot set property "autoComplete" of undefined`

in this context (global.autocomplete... line
```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global.autoComplete = factory());
}(undefined, (function () {
```

**Comment by TarekRaafat** [comment]
Please share your rollup config file if possible along with your dependencies, in order for me to be able to reproduce.

**Comment by mikob** [comment]
Np. Here is the rollup config, but I don't think anything here is unusual:

```
import html from 'rollup-plugin-html';
import typescript from 'rollup-plugin-typescript';
import resolve from 'rollup-plugin-node-resolve';
import globby from 'globby';

export default {
	input: globby.sync('src/modules/*'),
	plugins: [
		resolve(),
		typescript(),
		html({
			include: '**/*.html',
			htmlMinifierOptions: {
                collapseWhitespace: true,
                collapseBooleanAttributes: true,
                conservativeCollapse: true,
				minifyJS: true,
				minifyCSS: true,
				removeComments: true,
            }
		}),
	],
	experimentalCodeSplitting: true,
	output: {
		dir: 'chrome-extension/dist/modules',
		entryFileNames: '[name].mjs',
		format: 'esm',
	}
}

```

**Comment by TarekRaafat** [comment]
Hello @mikob, do you still have this `Runtime Error` issue?

**Comment by mikob** [comment]
Not sure, I'm not using this anymore. I'll close!

**Comment by d3pendent** [comment]
For everyone who might stumble over this issue:

Using rollup and getting `Error: 'default' is not exported by node_modules/@tarekraafat/autocomplete.
js/dist/js/autoComplete.js` ? 

You should use the plugin **commonjs** with **namedExports** in your **rollup** config.
NPM Package for common js rollup plugin: **rollup-plugin-commonjs**
```
...
    const plugins = [
        commonjs({
            namedExports: {
                '@tarekraafat/autocomplete.js': ['AutoCompleteJS']
            }
        })
    ];
...


```
then you can use `import AutoCompleteJS from '@tarekraafat/autocomplete.js'` un you js file.

instead of _AutoCompleteJS_ you can use whatever name you want.

Hope this helps ;)
