### ISSUE TITLE
Support for multiple fields on the same page.

### ISSUE THREAD

**Issue by crazy4groovy** [TarekRaafat/autoComplete.js#82]
**Is your feature request related to a problem? Please describe.**

I'm trying to hook up autocomplete to multiple input fields (user names) on the page.

**Thoroughly describe the solution you'd like**

`selector: () => document.querySelectorAll("input.name")`

**Please provide a few use cases for this feature**
- Forms with multiple rows of input fields, each field represents a finite set of possible suggested values (like known names)

**Please Describe alternatives you've considered**

**Additional context**

Currently throwing errors such as `TypeError: l.addEventListener is not a function`

**Comment by EmilStenstrom** [comment]
An alternative way to accomplish this: Make sure each field has an unique ID, and instantiate autcomplete once for each field. I have it working on two separate fields on the same page, using this technique.

**Comment by TarekRaafat** [comment]
Thanks @EmilStenstrom, adding to you your [example](https://jsfiddle.net/tarekraafat/6p5j4Lzh/2/) for achieving it.

Cheers!
