### ISSUE TITLE
Default results

### ISSUE THREAD

**Issue by zippy84** [TarekRaafat/autoComplete.js#83]
Hello.

Is there a way to setup a default-list, that is shown, when the user focuses the input? The list should be only visible, when there is no input. When input.length > threshold, the function behind data.src should be called.

**Comment by zippy84** [comment]
Found a way! Thanks for adding the trigger-option :+1:

**Comment by ljcp** [comment]
here is example for showing results on focus
```
      trigger: {
        event: ["input", "focusin"],
        condition:(query) => {
          return true;
        }
      }
```
