### ISSUE TITLE
Allow running autocomplete on a textarea

### ISSUE THREAD

**Issue by EmilStenstrom** [TarekRaafat/autoComplete.js#86]
Thank you for a great library! I don't think people working on side projects like this get even nearly the credit they deserve! 🥇 

**Is your feature request related to a problem? Please describe.**
When assigning autoComplete.js to a textarea, the correct ajax request gets sent, but nothing is rendered. Changing from textarea to input makes things work.

**Thoroughly Describe the solution you'd like**
That ´<textarea id="autocomplete"></textarea>´ worked exactly the same as `<input type="text" id="autocomplete>`.

**Please provide a few use cases for this feature**
1. I have an app where user can type in feature requests, and I would like to do an automatic search for duplicates in my database. Problem is that the description texts can be quite long, and I would like to be able to wrap the text in them. Seems inputs can't be wrapped with CSS, so I have to use a textarea.

**Please Describe alternatives you've considered**
I have not considered any alternative, happy to try them out if someone has one!

**Example code**
Here's an example as jsFiddle that works with an input, but doesn't work with a textarea: https://jsfiddle.net/ohckxy7v/2/

**Comment by TarekRaafat** [comment]
Hello @EmilStenstrom,

Thank you so much, I'm very glad that `autoComoplete.js` came in handy for you!

Unfortunately, `textarea` is not supported currently but there is an alternative that's more flexible than `textarea` which is `contenteditable` attribute.

You could add `contenteditable="true"` attribute to any of these type of elements `div`, `span`, `p`, `article`, etc.. and they will become editable multi-line text area which I guess would solve your issue.

MDN reference [contenteditable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable)
w3schools reference [contenteditable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable)

Modified [Demo](https://jsfiddle.net/tarekraafat/6p5j4Lzh/1/)

Kindly try this method and let me know if it works for you as expected or not.


Cheers, Have a good day! :)

**Comment by EmilStenstrom** [comment]
Thanks for such a quick reply! I'm not sure contenteditable will work, because this is part of a form that will likely get submitted if there are no duplicates. Let me show my use-case with an image to make it clearer:
<img width="874" alt="bild" src="https://user-images.githubusercontent.com/224130/68530845-825f5c80-030c-11ea-96bb-2b03949d40af.png">

On the left side you are filling in a form, on the right side the autocompleted results shows up. If none of the autocompleted fields match, you click "Log Request" and the form is submitted.

The problem with contenteditable is that it doesn't get submitted with the form. So in that case I would need to copy the contents of the field, clean it from unwanted HTML the user might have pasted, and insert it into a field that gets submitted.

I think it would be easier to just mirror the textarea into an input, and somehow trigger autoComplete.js that way...

**Comment by TarekRaafat** [comment]
To save you the hassle of the workaround I've added support to `Textarea` input field and because I believe that your use case could be recurring with other developers as well.

So now you can just through `autoComplete.js` almost to any kind of `HTML` element and you'll have it up and running OTB.

v7.2.0 [Github](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v7.2.0), [CDN](https://www.jsdelivr.com/package/npm/@tarekraafat/autocomplete.js), [NPM](https://www.npmjs.com/package/@tarekraafat/autocomplete.js)

Try it and let me know how it went.

Cheers! :)

**Comment by EmilStenstrom** [comment]
Wow, that works perfectly! I have mixed impressions of other autocomplete libraries in the past, but this one Just Works™️, super impressive! :)

Thanks again!

**Comment by TarekRaafat** [comment]
Great! always glad to help. :relaxed:

I like the slogan by the way "Just Works!" :boom:

Cheers man, have a good one!
