### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by cvaize** [TarekRaafat/autoComplete.js#87]
![image](https://user-images.githubusercontent.com/26907947/69009285-ae668780-0975-11ea-8979-b897015b5306.png)

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/69009291-c938fc00-0975-11ea-85eb-786a2dec19e1.png)
![image](https://user-images.githubusercontent.com/26907947/69009294-ce964680-0975-11ea-9f9f-aee21bf04736.png)

**Comment by TarekRaafat** [comment]
Hello @cvaize,

Make sure your function `S_CHECKOUT_ADDRESS()` returns element selector as shown below.

```js
selector: () => {
  return document.querySelector("#autoComplete");
},
```

Check your function and let me know.

Good day! :)

**Comment by cvaize** [comment]
@TarekRaafat Thanks, I already used another library, hope this issue will help other people!
