### ISSUE TITLE
onInit Callback

### ISSUE THREAD

**Issue by cedbesafilm** [TarekRaafat/autoComplete.js#89]
Could be useful to have a callback when an istance is initialized

**Comment by TarekRaafat** [comment]
Hello @cedbesafilm,

Thanks for your suggestion, I'd appreciate if you could back it up with a use case.

Good day, cheers! :)

**Comment by cedbesafilm** [comment]
in my app autocompletes are build dinamically based on some js objects, first i build the input element and last i create autocomplete
before i can dinamically set value to autocomplete i have to wait that autocomplete are instantiated otherwise i have referenceError

now i have a counter to autocomplete to be build and a setTimeout to wait autocomplete is really instantiated
But with an onInit callback i can delete the timeout

**Comment by arnav13081994** [comment]
Can't you wrap the autocomplete configuration in a function and you simply call the function whenever that JS object gets completed etc?

**Comment by cedbesafilm** [comment]
is what i do but with a counter....but I saw that if my app tries to set a value immediately after the counter goes to 0 i have a referenceError so I had to add a 200ms timeout to prevent this from happening


for me it is not a big problem but it made me think that such a function was useful 😄

**Comment by arnav13081994** [comment]
Ah ok. It's just that my use-case also involves firing multiple autocomplete instances dynamically but I have never encountered your error. But okay.

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)

**Comment by d3pendent** [comment]
Could anybody tell me how to make there events work? I couldn't find anything about the life cycle events in the documentation.
when are they fired, on what element should I listen to. 
I can't seem to get any event data.
