### ISSUE TITLE
Possibility to change the icon, color easily

### ISSUE THREAD

**Issue by ikkiphoenix** [TarekRaafat/autoComplete.js#90]
Hello,

I think it will very good if we can very easily modify all the css like we want. 
Maybe it will be better to handle with classes the css and not with the id autocomplete.

Thanks for your project.

**Comment by TarekRaafat** [comment]
Hello @ikkiphoenix,

Having the styling layer `CSS` separated from the logic layer of the library proved to be the best practice in terms of maintenance and performance.

Yet, you can still override the default style that ships with `autoComplete.js` out of the box or even you can use a totally different `CSS` sheet instead.

This way you get more control over the style/looks of your `autoComplete.js`.

So, I don't see combining the style and logic together something that would come anytime soon unless there is a very valid reason to do so.


Thank you for your suggestion.

Have a nice day, Cheers! :)
