### ISSUE TITLE
Use a default style more neutral

### ISSUE THREAD

**Issue by luizbills** [TarekRaafat/autoComplete.js#92]
The current `autoComplete.css` is very opinionated

**Comment by TarekRaafat** [comment]
Hello @luizbills,

I would appreciate it if you could be more specific.

Cheers! :)

**Comment by luizbills** [comment]
I can't include this style in any site... and users should not have to keep writing css whenever they want to use this library.
![image](https://user-images.githubusercontent.com/1798830/70616292-e1a2dc00-1bec-11ea-9925-1eab43aaf253.png)
You need a "more default" style, less opinionated

**Comment by TarekRaafat** [comment]
@luizbills I get your point, and I agree with you.

I'll make sure to add another "Plain/Default" style to the library next update.

Please, feel free to share any style suggestions you might have in mind, it would be so much helpful.

Cheers, and have a good day! :)

**Comment by digiiitalmb** [comment]
I second that, more conservative styling would be appreciated

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0) | [autoComplete.01.css](https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@8.1.0/dist/css/autoComplete.01.css)
[v8.1](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.1.0) | [autoComplete.02.css](https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@8.1.0/dist/css/autoComplete.02.css)
