### ISSUE TITLE
Missing option to ignore diacritics

### ISSUE THREAD

**Issue by svkmedia** [TarekRaafat/autoComplete.js#93]
I'm really missing option to ignore diacritics. 

Example: 
I'm using API calls to get results with a filter on backend. But in my DB results are stored with diacritics. If user searches without diacritics I'm not able to show him results from DB. My API call gets many results but JS filters these results with no match. 
I know highlight will not work anymore but at least user will gets results.

Solution:
I would prefer the possibility to define search method callback in options. If not present use default...

**Comment by TarekRaafat** [comment]
Hello @svkmedia,

Definitely "Diacritics" support will be included in the coming update, just exploring the best way of doing it currently and will be implemented in the new version.

Cheers, have a nice day! :)

**Comment by svkmedia** [comment]
Thank you for info

**Comment by TarekRaafat** [comment]
@svkmedia for the time being you could use the `query` API as shown below for the results you're after.

```js
query: {
  manipulate: function (query) {
    return query.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  },
}
```

Try it and let me know how it worked with you.

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
