### ISSUE TITLE
onSelection also detects right mouse button

### ISSUE THREAD

**Issue by ghost** [TarekRaafat/autoComplete.js#94]
- [x] **System Information**
 - [x] Firefox 71 on Mac OS
- [x] **Describe the bug**
When I click on an result with my right mouse button it toggles onSelection.

- [x] **Expected behavior**
It should only toggle on left mouse clicks

**Comment by TarekRaafat** [comment]
Hello @drankje,

Thanks for reporting that issue that I was not aware of frankly, but will make sure to get it fixed in the coming update.


Cheers, have a nice day!  :)

**Comment by drankje** [comment]
https://github.com/TarekRaafat/autoComplete.js/blob/c936ce1bf94df59c53cd0168928e38480119e2be/dist/js/autoComplete.js#L82

You could pass eventData trough a function, on event.type === "mousedown", which should return if (eventData.button === 1)

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
