### ISSUE TITLE
multiple instances create resultsList with same id 'autoComplete_list'

### ISSUE THREAD

**Issue by Monokai** [TarekRaafat/autoComplete.js#97]
I have multiple instances of autoComplete.js running, but they each generate a resultsList div with id `autoComplete_list`. I cannot find where I can change this.

I'm using this:

```js
resultsList: {
	render   : true,
	container: source => {
		$(source).attribute('class', 'js-results');
	},
	element    : 'ul',
	destination: this.$list[0]
}
```

Any idea where to specify a custom id or just skip it altogether?

**Comment by TarekRaafat** [comment]
Hello @Monokai,

The below code removes the `id` attribute entirely,  try it and let me know how it went.  

```js
resultsList: {
	render   : true,
	container: source => {
                $(source).removeAttr('id');
		$(source).attribute('class', 'js-results');
	},
	element    : 'ul',
	destination: this.$list[0]
}
```

Cheers, have a nice day! :)

**Comment by Monokai** [comment]
Can't believe I missed that :) Thanks!
