### ISSUE TITLE
Use own CSS classes

### ISSUE THREAD

**Issue by Lirux** [TarekRaafat/autoComplete.js#98]
When I'm not mistaken it's currently not possible to change these CSS classes.

```
var select = {
    resultsList: "autoComplete_list",
    result: "autoComplete_result",
    highlight: "autoComplete_highlighted",
    selectedResult: "autoComplete_selected"
};
```
It would be nice If it's possible to change them while initializing autoComplete.

Use case is for utility-first CSS frameworks like Tailwind.

Currently I just hardcoded it:

```
var select = {
    resultsList: "autoComplete_list",
    result: "autoComplete_result",
    highlight: "underline",
    selectedResult: "bg-gray-200"
};
```

**Comment by TarekRaafat** [comment]
[v8.0](https://github.com/TarekRaafat/autoComplete.js/releases/tag/v8.0.0)
