### ISSUE TITLE
record.toLowerCase is not a function

### ISSUE THREAD

**Issue by ross-oreto** [TarekRaafat/autoComplete.js#99]
- [ ] **System Information**
  - [ ] Chrome Version 79.0.3945.130 (Official Build) (64-bit)
  - [ ] Manjaro Cinamon 64 bit

- [ ] **Describe the bug**
 - using autoComplete version 7.2.0
  - same as issue: https://github.com/TarekRaafat/autoComplete.js/issues/38
```
Error in js console:
autoComplete.js:283 Uncaught (in promise) TypeError: record.toLowerCase is not a function
    at autoComplete.search (autoComplete.js:283)
    at search (autoComplete.js:318)
    at autoComplete.js:359
    at Array.filter (<anonymous>)
    at autoComplete.js:314
    at new Promise (<anonymous>)
    at autoComplete.listMatchedResults (autoComplete.js:312)
    at exec (autoComplete.js:427)
    at autoComplete.js:435
```

- [ ] **To Reproduce**
Steps to reproduce the behavior: <!-- Example below-!>
- create html input
```
    <input id="autoComplete" tabindex="1">
```
- create autocomplete
```
    new autoComplete({
        data: {
            src: [{test:"TEST"}, {test:"ING"}]
        }
        , key: ["test"]
        , cache: false
    });
```

- [ ] **Expected behavior**
Test suggestions should appear

**Comment by TarekRaafat** [comment]
Hello @ross-oreto,

The bug your getting is an issue of a typo.

You're including `key` and `cache` as an `autoComplete.js` configuration, not as a `data` configuration as they should be as shown in the code below.

```js
const autoCompletejs = new autoComplete({
 data: {
  src: [{ test: "TEST" }, { test: "ING" }],
  key: ["test"],
  cache: false
 }
});
```

Please, try the above code and let me know how it worked with you.

Cheers, have a nice day! :)

**Comment by ross-oreto** [comment]
Thanks that was the issue :)

**Comment by petercutting** [comment]
related to this. if the "key" data attribute has type integer (number?) then this line fails

var recordLowerCase = record.toLowerCase();

a simple fix is

var recordLowerCase = (record+"").toLowerCase();

**Comment by kevinfilteau** [comment]
Or don't add the integer to the key list.
